// Generated by scripts/import_style_csvs.py. Do not edit by hand.
export const styleSeedData = [
  {
    "id": "RING-001",
    "category": "ring",
    "subcategory": "engagementRing",
    "coverImage": "/assets/designs/BE1D5320_white_Round_top_2_carat.jpg",
    "media": [
      {
        "kind": "image",
        "src": "/assets/designs/BE1D5320_white_Round_top_2_carat.jpg"
      },
      {
        "kind": "image",
        "src": "/assets/designs/BE1D5320_EM_200ct_white_side1.jpg"
      },
      {
        "kind": "image",
        "src": "/assets/designs/BE1D5320_EM_200ct_white_side2.jpg"
      }
    ],
    "mediaComplete": true,
    "metalOptions": [
      "18kw",
      "18ky",
      "18kr",
      "pt"
    ],
    "estWeightG": 4.2,
    "laborUsd": 95,
    "leadDays": 12,
    "availableForSale": true,
    "published": true,
    "supplierEvidence": "https://www.brilliantearth.com/Opera-Three-Stone-Diamond-Ring-White-Gold-BE1D5320-8032928/",
    "firstQuoteAt": "2026-06-27",
    "name": {
      "en": "Classic Four-Prong Three Stone",
      "ko": "클래식 4프롱 쓰리 스톤",
      "zh": "经典 四爪 三石",
      "es": "clásico cuatro garras tres piedras"
    },
    "detailLabel": {
      "en": "Custom starter design",
      "ko": "맞춤 시작 디자인",
      "zh": "定制起点设计",
      "es": "Diseño inicial personalizado"
    },
    "description": {
      "en": "This is a sample starting point, not a limit. Share references and we can adjust shape, scale, stones, metal, and finish after review.",
      "ko": "이 디자인은 제한이 아니라 시작점입니다. 원하는 레퍼런스를 보내주시면 형태, 크기, 스톤, 메탈, 마감을 검토 후 조정할 수 있습니다.",
      "zh": "这是起点样例，不是限制。上传参考后，我们可评估并调整造型、尺寸、宝石、金属与细节。",
      "es": "Este diseño es un punto de partida, no un límite. Comparte referencias y ajustamos forma, escala, piedras, metal y acabado tras revisar."
    },
    "flexibleText": {
      "en": "Shape, stone, metal, scale",
      "ko": "형태, 스톤, 메탈, 크기",
      "zh": "造型、宝石、金属、比例",
      "es": "Forma, piedra, metal, escala"
    },
    "beforeProductionText": {
      "en": "Quote and CAD approval",
      "ko": "견적 및 CAD 승인",
      "zh": "报价与 CAD 确认",
      "es": "Cotización y aprobación CAD"
    }
  },
  {
    "id": "RING-026",
    "category": "ring",
    "subcategory": "engagementRing",
    "coverImage": "/assets/designs/BE1D322_yellow_Emerald_top_2_carat.jpg",
    "media": [
      {
        "kind": "image",
        "src": "/assets/designs/BE1D322_yellow_Emerald_top_2_carat.jpg"
      },
      {
        "kind": "image",
        "src": "/assets/designs/BE1D322_EM_200ct_yellow_side1.jpg"
      },
      {
        "kind": "image",
        "src": "/assets/designs/BE1D322_EM_200ct_yellow_side2.jpg"
      }
    ],
    "mediaComplete": true,
    "metalOptions": [
      "18kw",
      "18ky",
      "18kr",
      "pt"
    ],
    "estWeightG": 4.2,
    "laborUsd": 95,
    "leadDays": 12,
    "availableForSale": true,
    "published": true,
    "supplierEvidence": "https://www.brilliantearth.com/Adorned-Opera-Three-Stone-Diamond-Ring-(1/2-ct.-tw.)-Gold-BE1D322-12694822/",
    "firstQuoteAt": "2026-06-27",
    "name": {
      "en": "Classic Four-Prong Hidden Halo Three Stone",
      "ko": "클래식 4프롱 히든 헤일로 쓰리 스톤",
      "zh": "经典 四爪 隐藏光环 三石",
      "es": "clásico cuatro garras halo oculto tres piedras"
    },
    "detailLabel": {
      "en": "Custom starter design",
      "ko": "맞춤 시작 디자인",
      "zh": "定制起点设计",
      "es": "Diseño inicial personalizado"
    },
    "description": {
      "en": "This is a sample starting point, not a limit. Share references and we can adjust shape, scale, stones, metal, and finish after review.",
      "ko": "이 디자인은 제한이 아니라 시작점입니다. 원하는 레퍼런스를 보내주시면 형태, 크기, 스톤, 메탈, 마감을 검토 후 조정할 수 있습니다.",
      "zh": "这是起点样例，不是限制。上传参考后，我们可评估并调整造型、尺寸、宝石、金属与细节。",
      "es": "Este diseño es un punto de partida, no un límite. Comparte referencias y ajustamos forma, escala, piedras, metal y acabado tras revisar."
    },
    "flexibleText": {
      "en": "Shape, stone, metal, scale",
      "ko": "형태, 스톤, 메탈, 크기",
      "zh": "造型、宝石、金属、比例",
      "es": "Forma, piedra, metal, escala"
    },
    "beforeProductionText": {
      "en": "Quote and CAD approval",
      "ko": "견적 및 CAD 승인",
      "zh": "报价与 CAD 确认",
      "es": "Cotización y aprobación CAD"
    }
  },
  {
    "id": "RING-002",
    "category": "ring",
    "subcategory": "engagementRing",
    "coverImage": "/assets/designs/BE121H6_white_Round_top_2_carat.jpg",
    "media": [
      {
        "kind": "image",
        "src": "/assets/designs/BE121H6_white_Round_top_2_carat.jpg"
      },
      {
        "kind": "image",
        "src": "/assets/designs/BE121H6_RD_200ct_white_side1.jpg"
      },
      {
        "kind": "image",
        "src": "/assets/designs/BE121H6_RD_200ct_white_side2.jpg"
      }
    ],
    "mediaComplete": true,
    "metalOptions": [
      "18kw",
      "18ky",
      "18kr",
      "pt"
    ],
    "estWeightG": 4.2,
    "laborUsd": 95,
    "leadDays": 12,
    "availableForSale": true,
    "published": true,
    "supplierEvidence": "https://www.brilliantearth.com/Classic-Six-Prong-Solitaire-Ring-White-Gold-BE121H6-1151509/",
    "firstQuoteAt": "2026-06-27",
    "name": {
      "en": "Classic Six-Prong Solitaire",
      "ko": "클래식 6프롱 솔리테어",
      "zh": "经典 六爪 单钻",
      "es": "clásico seis garras solitario"
    },
    "detailLabel": {
      "en": "Custom starter design",
      "ko": "맞춤 시작 디자인",
      "zh": "定制起点设计",
      "es": "Diseño inicial personalizado"
    },
    "description": {
      "en": "This is a sample starting point, not a limit. Share references and we can adjust shape, scale, stones, metal, and finish after review.",
      "ko": "이 디자인은 제한이 아니라 시작점입니다. 원하는 레퍼런스를 보내주시면 형태, 크기, 스톤, 메탈, 마감을 검토 후 조정할 수 있습니다.",
      "zh": "这是起点样例，不是限制。上传参考后，我们可评估并调整造型、尺寸、宝石、金属与细节。",
      "es": "Este diseño es un punto de partida, no un límite. Comparte referencias y ajustamos forma, escala, piedras, metal y acabado tras revisar."
    },
    "flexibleText": {
      "en": "Shape, stone, metal, scale",
      "ko": "형태, 스톤, 메탈, 크기",
      "zh": "造型、宝石、金属、比例",
      "es": "Forma, piedra, metal, escala"
    },
    "beforeProductionText": {
      "en": "Quote and CAD approval",
      "ko": "견적 및 CAD 승인",
      "zh": "报价与 CAD 确认",
      "es": "Cotización y aprobación CAD"
    }
  },
  {
    "id": "RING-003",
    "category": "ring",
    "subcategory": "engagementRing",
    "coverImage": "/assets/designs/BE1D879_white_Emerald_top_2_carat.jpg",
    "media": [
      {
        "kind": "image",
        "src": "/assets/designs/BE1D879_white_Emerald_top_2_carat.jpg"
      },
      {
        "kind": "image",
        "src": "/assets/designs/BE1D879_EM_200ct_white_side1.jpg"
      },
      {
        "kind": "image",
        "src": "/assets/designs/BE1D879_EM_200ct_white_side2.jpg"
      }
    ],
    "mediaComplete": true,
    "metalOptions": [
      "18kw",
      "18ky",
      "18kr",
      "pt"
    ],
    "estWeightG": 4.2,
    "laborUsd": 95,
    "leadDays": 12,
    "availableForSale": true,
    "published": true,
    "supplierEvidence": "https://www.brilliantearth.com/Symphony-Tapered-Baguette-Three-Stone-Diamond-Ring-(1/2-ct.-tw.)-White-Gold-BE1D879-12137289/",
    "firstQuoteAt": "2026-06-27",
    "name": {
      "en": "Classic Four-Prong Side Stone",
      "ko": "클래식 4프롱 사이드 스톤",
      "zh": "经典 四爪 侧石",
      "es": "clásico cuatro garras piedra lateral"
    },
    "detailLabel": {
      "en": "Custom starter design",
      "ko": "맞춤 시작 디자인",
      "zh": "定制起点设计",
      "es": "Diseño inicial personalizado"
    },
    "description": {
      "en": "This is a sample starting point, not a limit. Share references and we can adjust shape, scale, stones, metal, and finish after review.",
      "ko": "이 디자인은 제한이 아니라 시작점입니다. 원하는 레퍼런스를 보내주시면 형태, 크기, 스톤, 메탈, 마감을 검토 후 조정할 수 있습니다.",
      "zh": "这是起点样例，不是限制。上传参考后，我们可评估并调整造型、尺寸、宝石、金属与细节。",
      "es": "Este diseño es un punto de partida, no un límite. Comparte referencias y ajustamos forma, escala, piedras, metal y acabado tras revisar."
    },
    "flexibleText": {
      "en": "Shape, stone, metal, scale",
      "ko": "형태, 스톤, 메탈, 크기",
      "zh": "造型、宝石、金属、比例",
      "es": "Forma, piedra, metal, escala"
    },
    "beforeProductionText": {
      "en": "Quote and CAD approval",
      "ko": "견적 및 CAD 승인",
      "zh": "报价与 CAD 确认",
      "es": "Cotización y aprobación CAD"
    }
  },
  {
    "id": "RING-004",
    "category": "ring",
    "subcategory": "engagementRing",
    "coverImage": "/assets/designs/BE1343_white_Oval_top_2_carat.jpg",
    "media": [
      {
        "kind": "image",
        "src": "/assets/designs/BE1343_white_Oval_top_2_carat.jpg"
      }
    ],
    "mediaComplete": true,
    "metalOptions": [
      "18kw",
      "18ky",
      "18kr",
      "pt"
    ],
    "estWeightG": 4.2,
    "laborUsd": 95,
    "leadDays": 12,
    "availableForSale": true,
    "published": true,
    "supplierEvidence": "https://www.bluenile.com/complete-jewel?j=17747604&s=11247872&utm_source=google&utm_medium=sem_unbranded_shopping&utm_campaign=semus_bn_google_us_engagement_engagement&utm_term=Natural_Engagement_Rings&utm_content=754884800603&gad_source=1&gad_campaignid=20398587011&gbraid=0AAAAAD_EjsjCNY_rUqDpgzv0YQF9TS4Na&gclid=Cj0KCQjwxvjRBhC2ARIsAI7KJa2Ow8sgzFq8phere0YKmg95n1J0hIXqTLh7JCXLYOIMqdFMewNInKUaAlbfEALw_wcB",
    "firstQuoteAt": "2026-06-27",
    "name": {
      "en": "Classic Four-Prong Solitaire",
      "ko": "클래식 4프롱 솔리테어",
      "zh": "经典 四爪 单钻",
      "es": "clásico cuatro garras solitario"
    },
    "detailLabel": {
      "en": "Custom starter design",
      "ko": "맞춤 시작 디자인",
      "zh": "定制起点设计",
      "es": "Diseño inicial personalizado"
    },
    "description": {
      "en": "This is a sample starting point, not a limit. Share references and we can adjust shape, scale, stones, metal, and finish after review.",
      "ko": "이 디자인은 제한이 아니라 시작점입니다. 원하는 레퍼런스를 보내주시면 형태, 크기, 스톤, 메탈, 마감을 검토 후 조정할 수 있습니다.",
      "zh": "这是起点样例，不是限制。上传参考后，我们可评估并调整造型、尺寸、宝石、金属与细节。",
      "es": "Este diseño es un punto de partida, no un límite. Comparte referencias y ajustamos forma, escala, piedras, metal y acabado tras revisar."
    },
    "flexibleText": {
      "en": "Shape, stone, metal, scale",
      "ko": "형태, 스톤, 메탈, 크기",
      "zh": "造型、宝石、金属、比例",
      "es": "Forma, piedra, metal, escala"
    },
    "beforeProductionText": {
      "en": "Quote and CAD approval",
      "ko": "견적 및 CAD 승인",
      "zh": "报价与 CAD 确认",
      "es": "Cotización y aprobación CAD"
    }
  },
  {
    "id": "RING-005",
    "category": "ring",
    "subcategory": "engagementRing",
    "coverImage": "/assets/designs/BE1761_white_Round_top_2_carat.jpg",
    "media": [
      {
        "kind": "image",
        "src": "/assets/designs/BE1761_white_Round_top_2_carat.jpg"
      },
      {
        "kind": "image",
        "src": "/assets/designs/BE1761_RD_200ct_white_side1.jpg"
      },
      {
        "kind": "image",
        "src": "/assets/designs/BE1761_RD_200ct_white_side2.jpg"
      }
    ],
    "mediaComplete": true,
    "metalOptions": [
      "18kw",
      "18ky",
      "18kr",
      "pt"
    ],
    "estWeightG": 4.2,
    "laborUsd": 95,
    "leadDays": 12,
    "availableForSale": true,
    "published": true,
    "supplierEvidence": "https://www.brilliantearth.com/Elodie-Cathedral-Solitaire-Ring-14K-White-Gold-BE1761-76788366/?utm_source=google&utm_medium=cpc&utm_campaign=SEM_PLA_US_ER_Conversion&utm_content=733311247350&gad_source=1&gad_campaignid=22248316004",
    "firstQuoteAt": "2026-06-27",
    "name": {
      "en": "Four-Prong Cathedral Solitaire",
      "ko": "4프롱 캐시드럴 솔리테어",
      "zh": "四爪 大教堂 单钻",
      "es": "cuatro garras catedral solitario"
    },
    "detailLabel": {
      "en": "Custom starter design",
      "ko": "맞춤 시작 디자인",
      "zh": "定制起点设计",
      "es": "Diseño inicial personalizado"
    },
    "description": {
      "en": "This is a sample starting point, not a limit. Share references and we can adjust shape, scale, stones, metal, and finish after review.",
      "ko": "이 디자인은 제한이 아니라 시작점입니다. 원하는 레퍼런스를 보내주시면 형태, 크기, 스톤, 메탈, 마감을 검토 후 조정할 수 있습니다.",
      "zh": "这是起点样例，不是限制。上传参考后，我们可评估并调整造型、尺寸、宝石、金属与细节。",
      "es": "Este diseño es un punto de partida, no un límite. Comparte referencias y ajustamos forma, escala, piedras, metal y acabado tras revisar."
    },
    "flexibleText": {
      "en": "Shape, stone, metal, scale",
      "ko": "형태, 스톤, 메탈, 크기",
      "zh": "造型、宝石、金属、比例",
      "es": "Forma, piedra, metal, escala"
    },
    "beforeProductionText": {
      "en": "Quote and CAD approval",
      "ko": "견적 및 CAD 승인",
      "zh": "报价与 CAD 确认",
      "es": "Cotización y aprobación CAD"
    }
  },
  {
    "id": "RING-006",
    "category": "ring",
    "subcategory": "engagementRing",
    "coverImage": "/assets/designs/BE1761_white_Marquise_top_2_carat.jpg",
    "media": [
      {
        "kind": "image",
        "src": "/assets/designs/BE1761_white_Marquise_top_2_carat.jpg"
      },
      {
        "kind": "image",
        "src": "/assets/designs/BE1761_MQ_200ct_white_side1.jpg"
      },
      {
        "kind": "image",
        "src": "/assets/designs/BE1761_MQ_200ct_white_side2.jpg"
      }
    ],
    "mediaComplete": true,
    "metalOptions": [
      "18kw",
      "18ky",
      "18kr",
      "pt"
    ],
    "estWeightG": 4.2,
    "laborUsd": 95,
    "leadDays": 12,
    "availableForSale": true,
    "published": true,
    "supplierEvidence": "https://www.brilliantearth.com/Elodie-Cathedral-Solitaire-Ring-Platinum-BE1761-25378093/",
    "firstQuoteAt": "2026-06-27",
    "name": {
      "en": "Six-Prong Cathedral Solitaire",
      "ko": "6프롱 캐시드럴 솔리테어",
      "zh": "六爪 大教堂 单钻",
      "es": "seis garras catedral solitario"
    },
    "detailLabel": {
      "en": "Custom starter design",
      "ko": "맞춤 시작 디자인",
      "zh": "定制起点设计",
      "es": "Diseño inicial personalizado"
    },
    "description": {
      "en": "This is a sample starting point, not a limit. Share references and we can adjust shape, scale, stones, metal, and finish after review.",
      "ko": "이 디자인은 제한이 아니라 시작점입니다. 원하는 레퍼런스를 보내주시면 형태, 크기, 스톤, 메탈, 마감을 검토 후 조정할 수 있습니다.",
      "zh": "这是起点样例，不是限制。上传参考后，我们可评估并调整造型、尺寸、宝石、金属与细节。",
      "es": "Este diseño es un punto de partida, no un límite. Comparte referencias y ajustamos forma, escala, piedras, metal y acabado tras revisar."
    },
    "flexibleText": {
      "en": "Shape, stone, metal, scale",
      "ko": "형태, 스톤, 메탈, 크기",
      "zh": "造型、宝石、金属、比例",
      "es": "Forma, piedra, metal, escala"
    },
    "beforeProductionText": {
      "en": "Quote and CAD approval",
      "ko": "견적 및 CAD 승인",
      "zh": "报价与 CAD 确认",
      "es": "Cotización y aprobación CAD"
    }
  },
  {
    "id": "RING-007",
    "category": "ring",
    "subcategory": "engagementRing",
    "coverImage": "/assets/designs/BE17652_white_Round_top_2_carat.jpg",
    "media": [
      {
        "kind": "image",
        "src": "/assets/designs/BE17652_white_Round_top_2_carat.jpg"
      },
      {
        "kind": "image",
        "src": "/assets/designs/BE17652_RD_200ct_white_side1.jpg"
      },
      {
        "kind": "image",
        "src": "/assets/designs/BE17652_RD_200ct_white_side2.jpg"
      }
    ],
    "mediaComplete": true,
    "metalOptions": [
      "18kw",
      "18ky",
      "18kr",
      "pt"
    ],
    "estWeightG": 4.2,
    "laborUsd": 95,
    "leadDays": 12,
    "availableForSale": true,
    "published": true,
    "supplierEvidence": "https://www.brilliantearth.com/Audrey-Perfect-Fit-1.4mm-Solitaire-Ring-14K-White-Gold-BE17652-76820235/",
    "firstQuoteAt": "2026-06-27",
    "name": {
      "en": "Four-Prong Basket Solitaire",
      "ko": "4프롱 바스켓 솔리테어",
      "zh": "四爪 篮式 单钻",
      "es": "cuatro garras basket solitario"
    },
    "detailLabel": {
      "en": "Custom starter design",
      "ko": "맞춤 시작 디자인",
      "zh": "定制起点设计",
      "es": "Diseño inicial personalizado"
    },
    "description": {
      "en": "This is a sample starting point, not a limit. Share references and we can adjust shape, scale, stones, metal, and finish after review.",
      "ko": "이 디자인은 제한이 아니라 시작점입니다. 원하는 레퍼런스를 보내주시면 형태, 크기, 스톤, 메탈, 마감을 검토 후 조정할 수 있습니다.",
      "zh": "这是起点样例，不是限制。上传参考后，我们可评估并调整造型、尺寸、宝石、金属与细节。",
      "es": "Este diseño es un punto de partida, no un límite. Comparte referencias y ajustamos forma, escala, piedras, metal y acabado tras revisar."
    },
    "flexibleText": {
      "en": "Shape, stone, metal, scale",
      "ko": "형태, 스톤, 메탈, 크기",
      "zh": "造型、宝石、金属、比例",
      "es": "Forma, piedra, metal, escala"
    },
    "beforeProductionText": {
      "en": "Quote and CAD approval",
      "ko": "견적 및 CAD 승인",
      "zh": "报价与 CAD 确认",
      "es": "Cotización y aprobación CAD"
    }
  },
  {
    "id": "RING-008",
    "category": "ring",
    "subcategory": "engagementRing",
    "coverImage": "/assets/designs/BE1D17653_yellow_Princess_top_2_carat.jpg",
    "media": [
      {
        "kind": "image",
        "src": "/assets/designs/BE1D17653_yellow_Princess_top_2_carat.jpg"
      },
      {
        "kind": "image",
        "src": "/assets/designs/BE1D17653_PR_200ct_yellow_side1.jpg"
      },
      {
        "kind": "image",
        "src": "/assets/designs/BE1D17653_PR_200ct_yellow_side2.jpg"
      }
    ],
    "mediaComplete": true,
    "metalOptions": [
      "18kw",
      "18ky",
      "18kr",
      "pt"
    ],
    "estWeightG": 4.2,
    "laborUsd": 95,
    "leadDays": 12,
    "availableForSale": true,
    "published": true,
    "supplierEvidence": "https://www.brilliantearth.com/Audrey-Perfect-Fit-Hidden-Halo-1.4mm-Diamond-Ring-14K-White-Gold-BE1D17653-76785919/?utm_source=google&utm_medium=cpc&utm_campaign=SEM_PLA_US_ER_Conversion&utm_content=733311247350&gad_source=1&gad_campaignid=22248316004",
    "firstQuoteAt": "2026-06-27",
    "name": {
      "en": "Four-Prong Hidden Halo Solitaire",
      "ko": "4프롱 히든 헤일로 솔리테어",
      "zh": "四爪 隐藏光环 单钻",
      "es": "cuatro garras halo oculto solitario"
    },
    "detailLabel": {
      "en": "Custom starter design",
      "ko": "맞춤 시작 디자인",
      "zh": "定制起点设计",
      "es": "Diseño inicial personalizado"
    },
    "description": {
      "en": "This is a sample starting point, not a limit. Share references and we can adjust shape, scale, stones, metal, and finish after review.",
      "ko": "이 디자인은 제한이 아니라 시작점입니다. 원하는 레퍼런스를 보내주시면 형태, 크기, 스톤, 메탈, 마감을 검토 후 조정할 수 있습니다.",
      "zh": "这是起点样例，不是限制。上传参考后，我们可评估并调整造型、尺寸、宝石、金属与细节。",
      "es": "Este diseño es un punto de partida, no un límite. Comparte referencias y ajustamos forma, escala, piedras, metal y acabado tras revisar."
    },
    "flexibleText": {
      "en": "Shape, stone, metal, scale",
      "ko": "형태, 스톤, 메탈, 크기",
      "zh": "造型、宝石、金属、比例",
      "es": "Forma, piedra, metal, escala"
    },
    "beforeProductionText": {
      "en": "Quote and CAD approval",
      "ko": "견적 및 CAD 승인",
      "zh": "报价与 CAD 确认",
      "es": "Cotización y aprobación CAD"
    }
  },
  {
    "id": "RING-009",
    "category": "ring",
    "subcategory": "engagementRing",
    "coverImage": "/assets/designs/BE1D9876_yellow_Pear_top_2_carat.jpg",
    "media": [
      {
        "kind": "image",
        "src": "/assets/designs/BE1D9876_yellow_Pear_top_2_carat.jpg"
      },
      {
        "kind": "image",
        "src": "/assets/designs/BE1D9876_PE_200ct_yellow_side1.jpg"
      },
      {
        "kind": "image",
        "src": "/assets/designs/BE1D9876_PE_200ct_yellow_side2.jpg"
      }
    ],
    "mediaComplete": true,
    "metalOptions": [
      "18kw",
      "18ky",
      "18kr",
      "pt"
    ],
    "estWeightG": 4.2,
    "laborUsd": 95,
    "leadDays": 12,
    "availableForSale": true,
    "published": true,
    "supplierEvidence": "https://www.brilliantearth.com/Sydney-Perfect-Fit-Hidden-Halo-Six-Prong-Diamond-Ring-14K-White-Gold-BE1D9876-76787118/?utm_source=google&utm_medium=cpc&utm_campaign=SEM_PLA_US_ER_Conversion&utm_content=733311247350&gad_source=4&gad_campaignid=22248316004",
    "firstQuoteAt": "2026-06-27",
    "name": {
      "en": "Six-Prong Hidden Halo Solitaire",
      "ko": "6프롱 히든 헤일로 솔리테어",
      "zh": "六爪 隐藏光环 单钻",
      "es": "seis garras halo oculto solitario"
    },
    "detailLabel": {
      "en": "Custom starter design",
      "ko": "맞춤 시작 디자인",
      "zh": "定制起点设计",
      "es": "Diseño inicial personalizado"
    },
    "description": {
      "en": "This is a sample starting point, not a limit. Share references and we can adjust shape, scale, stones, metal, and finish after review.",
      "ko": "이 디자인은 제한이 아니라 시작점입니다. 원하는 레퍼런스를 보내주시면 형태, 크기, 스톤, 메탈, 마감을 검토 후 조정할 수 있습니다.",
      "zh": "这是起点样例，不是限制。上传参考后，我们可评估并调整造型、尺寸、宝石、金属与细节。",
      "es": "Este diseño es un punto de partida, no un límite. Comparte referencias y ajustamos forma, escala, piedras, metal y acabado tras revisar."
    },
    "flexibleText": {
      "en": "Shape, stone, metal, scale",
      "ko": "형태, 스톤, 메탈, 크기",
      "zh": "造型、宝石、金属、比例",
      "es": "Forma, piedra, metal, escala"
    },
    "beforeProductionText": {
      "en": "Quote and CAD approval",
      "ko": "견적 및 CAD 승인",
      "zh": "报价与 CAD 确认",
      "es": "Cotización y aprobación CAD"
    }
  },
  {
    "id": "RING-010",
    "category": "ring",
    "subcategory": "engagementRing",
    "coverImage": "/assets/designs/BE1PD25R25_white_Round_top_2_carat.jpg",
    "media": [
      {
        "kind": "image",
        "src": "/assets/designs/BE1PD25R25_white_Round_top_2_carat.jpg"
      },
      {
        "kind": "image",
        "src": "/assets/designs/BE1PD25R25_RD_200ct_white_side1.jpg"
      },
      {
        "kind": "image",
        "src": "/assets/designs/BE1PD25R25_RD_200ct_white_side2.jpg"
      }
    ],
    "mediaComplete": true,
    "metalOptions": [
      "18kw",
      "18ky",
      "18kr",
      "pt"
    ],
    "estWeightG": 4.2,
    "laborUsd": 95,
    "leadDays": 12,
    "availableForSale": true,
    "published": true,
    "supplierEvidence": "https://www.brilliantearth.com/Petite-Shared-Prong-Half-Coverage-Diamond-Ring-14K-White-Gold-BE1PD25R25-76788913/",
    "firstQuoteAt": "2026-06-27",
    "name": {
      "en": "Four-Prong Half-Eternity Pavé Solitaire",
      "ko": "4프롱 하프 이터니티 파베 솔리테어",
      "zh": "四爪 半永恒 密钉 单钻",
      "es": "cuatro garras medio eternity pavé solitario"
    },
    "detailLabel": {
      "en": "Custom starter design",
      "ko": "맞춤 시작 디자인",
      "zh": "定制起点设计",
      "es": "Diseño inicial personalizado"
    },
    "description": {
      "en": "This is a sample starting point, not a limit. Share references and we can adjust shape, scale, stones, metal, and finish after review.",
      "ko": "이 디자인은 제한이 아니라 시작점입니다. 원하는 레퍼런스를 보내주시면 형태, 크기, 스톤, 메탈, 마감을 검토 후 조정할 수 있습니다.",
      "zh": "这是起点样例，不是限制。上传参考后，我们可评估并调整造型、尺寸、宝石、金属与细节。",
      "es": "Este diseño es un punto de partida, no un límite. Comparte referencias y ajustamos forma, escala, piedras, metal y acabado tras revisar."
    },
    "flexibleText": {
      "en": "Shape, stone, metal, scale",
      "ko": "형태, 스톤, 메탈, 크기",
      "zh": "造型、宝石、金属、比例",
      "es": "Forma, piedra, metal, escala"
    },
    "beforeProductionText": {
      "en": "Quote and CAD approval",
      "ko": "견적 및 CAD 승인",
      "zh": "报价与 CAD 确认",
      "es": "Cotización y aprobación CAD"
    }
  },
  {
    "id": "RING-011",
    "category": "ring",
    "subcategory": "engagementRing",
    "coverImage": "/assets/designs/BE1D166_yellow_Round_top_2_carat.jpg",
    "media": [
      {
        "kind": "image",
        "src": "/assets/designs/BE1D166_yellow_Round_top_2_carat.jpg"
      },
      {
        "kind": "image",
        "src": "/assets/designs/BE1D166_RD_200ct_yellow_side1.jpg"
      },
      {
        "kind": "image",
        "src": "/assets/designs/BE1D166_RD_200ct_yellow_side2.jpg"
      }
    ],
    "mediaComplete": true,
    "metalOptions": [
      "18kw",
      "18ky",
      "18kr",
      "pt"
    ],
    "estWeightG": 4.2,
    "laborUsd": 95,
    "leadDays": 12,
    "availableForSale": true,
    "published": true,
    "supplierEvidence": "https://www.brilliantearth.com/Cambria-Halo-Diamond-Ring-White-Gold-BE1D166-4896696/",
    "firstQuoteAt": "2026-06-27",
    "name": {
      "en": "Half-Eternity Pavé Halo",
      "ko": "하프 이터니티 파베 헤일로",
      "zh": "半永恒 密钉 光环",
      "es": "medio eternity pavé halo"
    },
    "detailLabel": {
      "en": "Custom starter design",
      "ko": "맞춤 시작 디자인",
      "zh": "定制起点设计",
      "es": "Diseño inicial personalizado"
    },
    "description": {
      "en": "This is a sample starting point, not a limit. Share references and we can adjust shape, scale, stones, metal, and finish after review.",
      "ko": "이 디자인은 제한이 아니라 시작점입니다. 원하는 레퍼런스를 보내주시면 형태, 크기, 스톤, 메탈, 마감을 검토 후 조정할 수 있습니다.",
      "zh": "这是起点样例，不是限制。上传参考后，我们可评估并调整造型、尺寸、宝石、金属与细节。",
      "es": "Este diseño es un punto de partida, no un límite. Comparte referencias y ajustamos forma, escala, piedras, metal y acabado tras revisar."
    },
    "flexibleText": {
      "en": "Shape, stone, metal, scale",
      "ko": "형태, 스톤, 메탈, 크기",
      "zh": "造型、宝石、金属、比例",
      "es": "Forma, piedra, metal, escala"
    },
    "beforeProductionText": {
      "en": "Quote and CAD approval",
      "ko": "견적 및 CAD 승인",
      "zh": "报价与 CAD 确认",
      "es": "Cotización y aprobación CAD"
    }
  },
  {
    "id": "RING-012",
    "category": "ring",
    "subcategory": "engagementRing",
    "coverImage": "/assets/designs/BE1D1602_yellow_Emerald_top_2_carat.jpg",
    "media": [
      {
        "kind": "image",
        "src": "/assets/designs/BE1D1602_yellow_Emerald_top_2_carat.jpg"
      },
      {
        "kind": "image",
        "src": "/assets/designs/BE1D1602_EM_200ct_yellow_side1.jpg"
      },
      {
        "kind": "image",
        "src": "/assets/designs/BE1D1602_EM_200ct_yellow_side2.jpg"
      }
    ],
    "mediaComplete": true,
    "metalOptions": [
      "18kw",
      "18ky",
      "18kr",
      "pt"
    ],
    "estWeightG": 4.2,
    "laborUsd": 95,
    "leadDays": 12,
    "availableForSale": true,
    "published": true,
    "supplierEvidence": "https://www.brilliantearth.com/Lyra-Three-Stone-Diamond-Ring-(1/4-ct.-tw.)-14K-White-Gold-BE1D1602-76788324/?utm_source=google&utm_medium=cpc&utm_campaign=SEM_PLA_US_ER_Conversion&utm_content=733311247380&gad_source=1&gad_campaignid=22248316004",
    "firstQuoteAt": "2026-06-27",
    "name": {
      "en": "Four-Prong Half-Eternity Pavé Three Stone",
      "ko": "4프롱 하프 이터니티 파베 쓰리 스톤",
      "zh": "四爪 半永恒 密钉 三石",
      "es": "cuatro garras medio eternity pavé tres piedras"
    },
    "detailLabel": {
      "en": "Custom starter design",
      "ko": "맞춤 시작 디자인",
      "zh": "定制起点设计",
      "es": "Diseño inicial personalizado"
    },
    "description": {
      "en": "This is a sample starting point, not a limit. Share references and we can adjust shape, scale, stones, metal, and finish after review.",
      "ko": "이 디자인은 제한이 아니라 시작점입니다. 원하는 레퍼런스를 보내주시면 형태, 크기, 스톤, 메탈, 마감을 검토 후 조정할 수 있습니다.",
      "zh": "这是起点样例，不是限制。上传参考后，我们可评估并调整造型、尺寸、宝石、金属与细节。",
      "es": "Este diseño es un punto de partida, no un límite. Comparte referencias y ajustamos forma, escala, piedras, metal y acabado tras revisar."
    },
    "flexibleText": {
      "en": "Shape, stone, metal, scale",
      "ko": "형태, 스톤, 메탈, 크기",
      "zh": "造型、宝石、金属、比例",
      "es": "Forma, piedra, metal, escala"
    },
    "beforeProductionText": {
      "en": "Quote and CAD approval",
      "ko": "견적 및 CAD 승인",
      "zh": "报价与 CAD 确认",
      "es": "Cotización y aprobación CAD"
    }
  },
  {
    "id": "RING-013",
    "category": "ring",
    "subcategory": "engagementRing",
    "coverImage": "/assets/designs/BE1D1516_white_Round_top_2_carat.jpg",
    "media": [
      {
        "kind": "image",
        "src": "/assets/designs/BE1D1516_white_Round_top_2_carat.jpg"
      },
      {
        "kind": "image",
        "src": "/assets/designs/BE1D1516_RD_200ct_white_side1.jpg"
      },
      {
        "kind": "image",
        "src": "/assets/designs/BE1D1516_RD_200ct_white_side2.jpg"
      }
    ],
    "mediaComplete": true,
    "metalOptions": [
      "18kw",
      "18ky",
      "18kr",
      "pt"
    ],
    "estWeightG": 4.2,
    "laborUsd": 95,
    "leadDays": 12,
    "availableForSale": true,
    "published": true,
    "supplierEvidence": "https://www.brilliantearth.com/Six-Prong-Petite-Shared-Prong-Diamond-Ring-(1/5-ct.-tw.)-14K-White-Gold-BE1D1516-76822931/",
    "firstQuoteAt": "2026-06-27",
    "name": {
      "en": "Six-Prong Half-Eternity Pavé Solitaire",
      "ko": "6프롱 하프 이터니티 파베 솔리테어",
      "zh": "六爪 半永恒 密钉 单钻",
      "es": "seis garras medio eternity pavé solitario"
    },
    "detailLabel": {
      "en": "Custom starter design",
      "ko": "맞춤 시작 디자인",
      "zh": "定制起点设计",
      "es": "Diseño inicial personalizado"
    },
    "description": {
      "en": "This is a sample starting point, not a limit. Share references and we can adjust shape, scale, stones, metal, and finish after review.",
      "ko": "이 디자인은 제한이 아니라 시작점입니다. 원하는 레퍼런스를 보내주시면 형태, 크기, 스톤, 메탈, 마감을 검토 후 조정할 수 있습니다.",
      "zh": "这是起点样例，不是限制。上传参考后，我们可评估并调整造型、尺寸、宝石、金属与细节。",
      "es": "Este diseño es un punto de partida, no un límite. Comparte referencias y ajustamos forma, escala, piedras, metal y acabado tras revisar."
    },
    "flexibleText": {
      "en": "Shape, stone, metal, scale",
      "ko": "형태, 스톤, 메탈, 크기",
      "zh": "造型、宝石、金属、比例",
      "es": "Forma, piedra, metal, escala"
    },
    "beforeProductionText": {
      "en": "Quote and CAD approval",
      "ko": "견적 및 CAD 승인",
      "zh": "报价与 CAD 确认",
      "es": "Cotización y aprobación CAD"
    }
  },
  {
    "id": "RING-014",
    "category": "ring",
    "subcategory": "engagementRing",
    "coverImage": "/assets/designs/BE1D2414_yellow_Emerald_top_2_carat.jpg",
    "media": [
      {
        "kind": "image",
        "src": "/assets/designs/BE1D2414_yellow_Emerald_top_2_carat.jpg"
      },
      {
        "kind": "image",
        "src": "/assets/designs/BE1D2414_EM_200ct_yellow_side1.jpg"
      },
      {
        "kind": "image",
        "src": "/assets/designs/BE1D2414_EM_200ct_yellow_side2.jpg"
      }
    ],
    "mediaComplete": true,
    "metalOptions": [
      "18kw",
      "18ky",
      "18kr",
      "pt"
    ],
    "estWeightG": 4.2,
    "laborUsd": 95,
    "leadDays": 12,
    "availableForSale": true,
    "published": true,
    "supplierEvidence": "https://www.brilliantearth.com/Perfect-Fit-Eternity-Diamond-Ring-(1-1/3-ct.-tw.)-14K-White-Gold-BE1D2414-76788451/?utm_source=google&utm_medium=cpc&utm_campaign=SEM_PLA_US_ER_Conversion&utm_content=733311247350&gad_source=1&gad_campaignid=22248316004",
    "firstQuoteAt": "2026-06-27",
    "name": {
      "en": "Four-Prong Full-Eternity Pavé Solitaire",
      "ko": "4프롱 풀 이터니티 파베 솔리테어",
      "zh": "四爪 全永恒 密钉 单钻",
      "es": "cuatro garras eternity completo pavé solitario"
    },
    "detailLabel": {
      "en": "Custom starter design",
      "ko": "맞춤 시작 디자인",
      "zh": "定制起点设计",
      "es": "Diseño inicial personalizado"
    },
    "description": {
      "en": "This is a sample starting point, not a limit. Share references and we can adjust shape, scale, stones, metal, and finish after review.",
      "ko": "이 디자인은 제한이 아니라 시작점입니다. 원하는 레퍼런스를 보내주시면 형태, 크기, 스톤, 메탈, 마감을 검토 후 조정할 수 있습니다.",
      "zh": "这是起点样例，不是限制。上传参考后，我们可评估并调整造型、尺寸、宝石、金属与细节。",
      "es": "Este diseño es un punto de partida, no un límite. Comparte referencias y ajustamos forma, escala, piedras, metal y acabado tras revisar."
    },
    "flexibleText": {
      "en": "Shape, stone, metal, scale",
      "ko": "형태, 스톤, 메탈, 크기",
      "zh": "造型、宝石、金属、比例",
      "es": "Forma, piedra, metal, escala"
    },
    "beforeProductionText": {
      "en": "Quote and CAD approval",
      "ko": "견적 및 CAD 승인",
      "zh": "报价与 CAD 确认",
      "es": "Cotización y aprobación CAD"
    }
  },
  {
    "id": "RING-015",
    "category": "ring",
    "subcategory": "engagementRing",
    "coverImage": "/assets/designs/BE1D64_RD_200ct_white_side1.jpg",
    "media": [
      {
        "kind": "image",
        "src": "/assets/designs/BE1D64_RD_200ct_white_side1.jpg"
      },
      {
        "kind": "image",
        "src": "/assets/designs/BE1D64_RD_200ct_yellow_side2.jpg"
      }
    ],
    "mediaComplete": true,
    "metalOptions": [
      "18kw",
      "18ky",
      "18kr",
      "pt"
    ],
    "estWeightG": 4.2,
    "laborUsd": 95,
    "leadDays": 12,
    "availableForSale": true,
    "published": true,
    "supplierEvidence": "https://www.brilliantearth.com/Waverly-Halo-Diamond-Ring-(1/2-ct.-tw.)-14K-White-Gold-BE1D64-76823653/?utm_source=google&utm_medium=cpc&utm_campaign=SEM_PLA_US_ER_Conversion&utm_content=733311247350&gad_source=1&gad_campaignid=22248316004",
    "firstQuoteAt": "2026-06-27",
    "name": {
      "en": "Three-Quarter Eternity Pavé Halo",
      "ko": "쓰리쿼터 이터니티 파베 헤일로",
      "zh": "四分之三永恒 密钉 光环",
      "es": "eternity tres cuartos pavé halo"
    },
    "detailLabel": {
      "en": "Custom starter design",
      "ko": "맞춤 시작 디자인",
      "zh": "定制起点设计",
      "es": "Diseño inicial personalizado"
    },
    "description": {
      "en": "This is a sample starting point, not a limit. Share references and we can adjust shape, scale, stones, metal, and finish after review.",
      "ko": "이 디자인은 제한이 아니라 시작점입니다. 원하는 레퍼런스를 보내주시면 형태, 크기, 스톤, 메탈, 마감을 검토 후 조정할 수 있습니다.",
      "zh": "这是起点样例，不是限制。上传参考后，我们可评估并调整造型、尺寸、宝石、金属与细节。",
      "es": "Este diseño es un punto de partida, no un límite. Comparte referencias y ajustamos forma, escala, piedras, metal y acabado tras revisar."
    },
    "flexibleText": {
      "en": "Shape, stone, metal, scale",
      "ko": "형태, 스톤, 메탈, 크기",
      "zh": "造型、宝石、金属、比例",
      "es": "Forma, piedra, metal, escala"
    },
    "beforeProductionText": {
      "en": "Quote and CAD approval",
      "ko": "견적 및 CAD 승인",
      "zh": "报价与 CAD 确认",
      "es": "Cotización y aprobación CAD"
    }
  },
  {
    "id": "RING-016",
    "category": "ring",
    "subcategory": "engagementRing",
    "coverImage": "/assets/designs/BE1D145_white_Oval_top_2_carat.jpg",
    "media": [
      {
        "kind": "image",
        "src": "/assets/designs/BE1D145_white_Oval_top_2_carat.jpg"
      },
      {
        "kind": "image",
        "src": "/assets/designs/BE1D145_OV_200ct_white_side2.jpg"
      }
    ],
    "mediaComplete": true,
    "metalOptions": [
      "18kw",
      "18ky",
      "18kr",
      "pt"
    ],
    "estWeightG": 4.2,
    "laborUsd": 95,
    "leadDays": 12,
    "availableForSale": true,
    "published": true,
    "supplierEvidence": "https://www.brilliantearth.com/Luxe-French-Pav%C3%A9-Perfect-Fit-Diamond-Ring-(1/2-ct.-tw.)-14K-White-Gold-BE1D145-76787082/?utm_source=google&utm_medium=cpc&utm_campaign=SEM_PLA_US_ER_Conversion&utm_content=733311247350&gad_source=1&gad_campaignid=22248316004",
    "firstQuoteAt": "2026-06-27",
    "name": {
      "en": "Four-Prong Three-Quarter Eternity Pavé Solitaire",
      "ko": "4프롱 쓰리쿼터 이터니티 파베 솔리테어",
      "zh": "四爪 四分之三永恒 密钉 单钻",
      "es": "cuatro garras eternity tres cuartos pavé solitario"
    },
    "detailLabel": {
      "en": "Custom starter design",
      "ko": "맞춤 시작 디자인",
      "zh": "定制起点设计",
      "es": "Diseño inicial personalizado"
    },
    "description": {
      "en": "This is a sample starting point, not a limit. Share references and we can adjust shape, scale, stones, metal, and finish after review.",
      "ko": "이 디자인은 제한이 아니라 시작점입니다. 원하는 레퍼런스를 보내주시면 형태, 크기, 스톤, 메탈, 마감을 검토 후 조정할 수 있습니다.",
      "zh": "这是起点样例，不是限制。上传参考后，我们可评估并调整造型、尺寸、宝石、金属与细节。",
      "es": "Este diseño es un punto de partida, no un límite. Comparte referencias y ajustamos forma, escala, piedras, metal y acabado tras revisar."
    },
    "flexibleText": {
      "en": "Shape, stone, metal, scale",
      "ko": "형태, 스톤, 메탈, 크기",
      "zh": "造型、宝石、金属、比例",
      "es": "Forma, piedra, metal, escala"
    },
    "beforeProductionText": {
      "en": "Quote and CAD approval",
      "ko": "견적 및 CAD 승인",
      "zh": "报价与 CAD 确认",
      "es": "Cotización y aprobación CAD"
    }
  },
  {
    "id": "RING-017",
    "category": "ring",
    "subcategory": "engagementRing",
    "coverImage": "/assets/designs/BE1D6362P_RD_200ct_white_side1.jpg",
    "media": [
      {
        "kind": "image",
        "src": "/assets/designs/BE1D6362P_RD_200ct_white_side1.jpg"
      },
      {
        "kind": "image",
        "src": "/assets/designs/BE1D6362P_RD_200ct_white_side2.jpg"
      }
    ],
    "mediaComplete": true,
    "metalOptions": [
      "18kw",
      "18ky",
      "18kr",
      "pt"
    ],
    "estWeightG": 4.2,
    "laborUsd": 95,
    "leadDays": 12,
    "availableForSale": true,
    "published": true,
    "supplierEvidence": "https://www.brilliantearth.com/Gala-Diamond-Ring-14K-White-Gold-BE1D6362P-76788400/?utm_source=google&utm_medium=cpc&utm_campaign=SEM_PLA_US_ER_Conversion&utm_content=733311247380&gad_source=1&gad_campaignid=22248316004",
    "firstQuoteAt": "2026-06-27",
    "name": {
      "en": "Three-Quarter Eternity Pavé Hidden Halo",
      "ko": "쓰리쿼터 이터니티 파베 히든 헤일로",
      "zh": "四分之三永恒 密钉 隐藏光环",
      "es": "eternity tres cuartos pavé halo oculto"
    },
    "detailLabel": {
      "en": "Custom starter design",
      "ko": "맞춤 시작 디자인",
      "zh": "定制起点设计",
      "es": "Diseño inicial personalizado"
    },
    "description": {
      "en": "This is a sample starting point, not a limit. Share references and we can adjust shape, scale, stones, metal, and finish after review.",
      "ko": "이 디자인은 제한이 아니라 시작점입니다. 원하는 레퍼런스를 보내주시면 형태, 크기, 스톤, 메탈, 마감을 검토 후 조정할 수 있습니다.",
      "zh": "这是起点样例，不是限制。上传参考后，我们可评估并调整造型、尺寸、宝石、金属与细节。",
      "es": "Este diseño es un punto de partida, no un límite. Comparte referencias y ajustamos forma, escala, piedras, metal y acabado tras revisar."
    },
    "flexibleText": {
      "en": "Shape, stone, metal, scale",
      "ko": "형태, 스톤, 메탈, 크기",
      "zh": "造型、宝石、金属、比例",
      "es": "Forma, piedra, metal, escala"
    },
    "beforeProductionText": {
      "en": "Quote and CAD approval",
      "ko": "견적 및 CAD 승인",
      "zh": "报价与 CAD 确认",
      "es": "Cotización y aprobación CAD"
    }
  },
  {
    "id": "RING-018",
    "category": "ring",
    "subcategory": "engagementRing",
    "coverImage": "/assets/designs/BE1524_yellow_Emerald_top_2_carat.jpg",
    "media": [
      {
        "kind": "image",
        "src": "/assets/designs/BE1524_yellow_Emerald_top_2_carat.jpg"
      },
      {
        "kind": "image",
        "src": "/assets/designs/BE1524_EM_200ct_yellow_side1.jpg"
      },
      {
        "kind": "image",
        "src": "/assets/designs/BE1524_EM_200ct_yellow_side2.jpg"
      }
    ],
    "mediaComplete": true,
    "metalOptions": [
      "18kw",
      "18ky",
      "18kr",
      "pt"
    ],
    "estWeightG": 4.2,
    "laborUsd": 95,
    "leadDays": 12,
    "availableForSale": true,
    "published": true,
    "supplierEvidence": "https://www.brilliantearth.com/Piper-Knife-Edge-Solitaire-Ring-14K-White-Gold-BE1524-76785969/",
    "firstQuoteAt": "2026-06-27",
    "name": {
      "en": "Four-Prong Knife Edge Solitaire",
      "ko": "4프롱 나이프 엣지 솔리테어",
      "zh": "四爪 刀锋 单钻",
      "es": "cuatro garras knife edge solitario"
    },
    "detailLabel": {
      "en": "Custom starter design",
      "ko": "맞춤 시작 디자인",
      "zh": "定制起点设计",
      "es": "Diseño inicial personalizado"
    },
    "description": {
      "en": "This is a sample starting point, not a limit. Share references and we can adjust shape, scale, stones, metal, and finish after review.",
      "ko": "이 디자인은 제한이 아니라 시작점입니다. 원하는 레퍼런스를 보내주시면 형태, 크기, 스톤, 메탈, 마감을 검토 후 조정할 수 있습니다.",
      "zh": "这是起点样例，不是限制。上传参考后，我们可评估并调整造型、尺寸、宝石、金属与细节。",
      "es": "Este diseño es un punto de partida, no un límite. Comparte referencias y ajustamos forma, escala, piedras, metal y acabado tras revisar."
    },
    "flexibleText": {
      "en": "Shape, stone, metal, scale",
      "ko": "형태, 스톤, 메탈, 크기",
      "zh": "造型、宝石、金属、比例",
      "es": "Forma, piedra, metal, escala"
    },
    "beforeProductionText": {
      "en": "Quote and CAD approval",
      "ko": "견적 및 CAD 승인",
      "zh": "报价与 CAD 确认",
      "es": "Cotización y aprobación CAD"
    }
  },
  {
    "id": "RING-019",
    "category": "ring",
    "subcategory": "engagementRing",
    "coverImage": "/assets/designs/BNS12xBNH01_M1_RND_DIM_wht_0100CT_W_W.001.jpg",
    "media": [
      {
        "kind": "image",
        "src": "/assets/designs/BNS12xBNH01_M1_RND_DIM_wht_0100CT_W_W.001.jpg"
      },
      {
        "kind": "image",
        "src": "/assets/designs/BNS12xBNH01_M1_RND_DIM_wht_0100CT_W_W.002.jpg"
      }
    ],
    "mediaComplete": true,
    "metalOptions": [
      "18kw",
      "18ky",
      "18kr",
      "pt"
    ],
    "estWeightG": 4.2,
    "laborUsd": 95,
    "leadDays": 12,
    "availableForSale": true,
    "published": true,
    "supplierEvidence": "https://www.bluenile.com/engagement-rings/custom-engagement-rings/knife-edge-pave-engagement-ring-4-prong-nouveau-head-item-293453?srsltid=AfmBOory28JlAQvU0305tHL_XcXe6wOg6cjmZJhqKF-_Um4SDwsPbGuqM5g",
    "firstQuoteAt": "2026-06-27",
    "name": {
      "en": "Four-Prong Knife Edge Pavé Three Stone",
      "ko": "4프롱 나이프 엣지 파베 쓰리 스톤",
      "zh": "四爪 刀锋 密钉 三石",
      "es": "cuatro garras knife edge pavé tres piedras"
    },
    "detailLabel": {
      "en": "Custom starter design",
      "ko": "맞춤 시작 디자인",
      "zh": "定制起点设计",
      "es": "Diseño inicial personalizado"
    },
    "description": {
      "en": "This is a sample starting point, not a limit. Share references and we can adjust shape, scale, stones, metal, and finish after review.",
      "ko": "이 디자인은 제한이 아니라 시작점입니다. 원하는 레퍼런스를 보내주시면 형태, 크기, 스톤, 메탈, 마감을 검토 후 조정할 수 있습니다.",
      "zh": "这是起点样例，不是限制。上传参考后，我们可评估并调整造型、尺寸、宝石、金属与细节。",
      "es": "Este diseño es un punto de partida, no un límite. Comparte referencias y ajustamos forma, escala, piedras, metal y acabado tras revisar."
    },
    "flexibleText": {
      "en": "Shape, stone, metal, scale",
      "ko": "형태, 스톤, 메탈, 크기",
      "zh": "造型、宝石、金属、比例",
      "es": "Forma, piedra, metal, escala"
    },
    "beforeProductionText": {
      "en": "Quote and CAD approval",
      "ko": "견적 및 CAD 승인",
      "zh": "报价与 CAD 确认",
      "es": "Cotización y aprobación CAD"
    }
  },
  {
    "id": "RING-020",
    "category": "ring",
    "subcategory": "engagementRing",
    "coverImage": "/assets/designs/six-prong-solitaire-engagement-ring-knife-edge-shank__02947.1783355634.jpg",
    "media": [
      {
        "kind": "image",
        "src": "/assets/designs/six-prong-solitaire-engagement-ring-knife-edge-shank__02947.1783355634.jpg"
      },
      {
        "kind": "image",
        "src": "/assets/designs/six-prong-solitaire-engagement-ring-knife-edge-shank-side__34860.1783355644.jpg"
      }
    ],
    "mediaComplete": true,
    "metalOptions": [
      "18kw",
      "18ky",
      "18kr",
      "pt"
    ],
    "estWeightG": 4.2,
    "laborUsd": 95,
    "leadDays": 12,
    "availableForSale": true,
    "published": true,
    "supplierEvidence": "https://www.jewelrypoint.com/6-prong-solitaire-engagement-ring-mounting-knife-edge-band/?gad_source=4&gad_campaignid=22384748286&gbraid=0AAAAAD9WMcceEy9yCQLhIAfq_rQg-yrWV&gclid=EAIaIQobChMI2Ni0s_TOlQMVRR6tBh1c4RRcEAQYAyABEgJqcvD_BwE",
    "firstQuoteAt": "2026-06-27",
    "name": {
      "en": "Six-Prong Knife Edge Solitaire",
      "ko": "6프롱 나이프 엣지 솔리테어",
      "zh": "六爪 刀锋 单钻",
      "es": "seis garras knife edge solitario"
    },
    "detailLabel": {
      "en": "Custom starter design",
      "ko": "맞춤 시작 디자인",
      "zh": "定制起点设计",
      "es": "Diseño inicial personalizado"
    },
    "description": {
      "en": "This is a sample starting point, not a limit. Share references and we can adjust shape, scale, stones, metal, and finish after review.",
      "ko": "이 디자인은 제한이 아니라 시작점입니다. 원하는 레퍼런스를 보내주시면 형태, 크기, 스톤, 메탈, 마감을 검토 후 조정할 수 있습니다.",
      "zh": "这是起点样例，不是限制。上传参考后，我们可评估并调整造型、尺寸、宝石、金属与细节。",
      "es": "Este diseño es un punto de partida, no un límite. Comparte referencias y ajustamos forma, escala, piedras, metal y acabado tras revisar."
    },
    "flexibleText": {
      "en": "Shape, stone, metal, scale",
      "ko": "형태, 스톤, 메탈, 크기",
      "zh": "造型、宝石、金属、比例",
      "es": "Forma, piedra, metal, escala"
    },
    "beforeProductionText": {
      "en": "Quote and CAD approval",
      "ko": "견적 및 CAD 승인",
      "zh": "报价与 CAD 确认",
      "es": "Cotización y aprobación CAD"
    }
  },
  {
    "id": "RING-021",
    "category": "ring",
    "subcategory": "engagementRing",
    "coverImage": "/assets/designs/BE1DT2686_white_Round_top_2_carat.jpg",
    "media": [
      {
        "kind": "image",
        "src": "/assets/designs/BE1DT2686_white_Round_top_2_carat.jpg"
      },
      {
        "kind": "image",
        "src": "/assets/designs/BE1DT2686_RD_200ct_white_side1.jpg"
      }
    ],
    "mediaComplete": true,
    "metalOptions": [
      "18kw",
      "18ky",
      "18kr",
      "pt"
    ],
    "estWeightG": 4.2,
    "laborUsd": 95,
    "leadDays": 12,
    "availableForSale": true,
    "published": true,
    "supplierEvidence": "https://www.brilliantearth.com/Tacori-Sculpted-Crescent-Knife-Edge-Diamond-Ring-White-Gold-BE1DT2686-12921130/",
    "firstQuoteAt": "2026-06-27",
    "name": {
      "en": "Four-Prong Knife Edge Pavé Solitaire",
      "ko": "4프롱 나이프 엣지 파베 솔리테어",
      "zh": "四爪 刀锋 密钉 单钻",
      "es": "cuatro garras knife edge pavé solitario"
    },
    "detailLabel": {
      "en": "Custom starter design",
      "ko": "맞춤 시작 디자인",
      "zh": "定制起点设计",
      "es": "Diseño inicial personalizado"
    },
    "description": {
      "en": "This is a sample starting point, not a limit. Share references and we can adjust shape, scale, stones, metal, and finish after review.",
      "ko": "이 디자인은 제한이 아니라 시작점입니다. 원하는 레퍼런스를 보내주시면 형태, 크기, 스톤, 메탈, 마감을 검토 후 조정할 수 있습니다.",
      "zh": "这是起点样例，不是限制。上传参考后，我们可评估并调整造型、尺寸、宝石、金属与细节。",
      "es": "Este diseño es un punto de partida, no un límite. Comparte referencias y ajustamos forma, escala, piedras, metal y acabado tras revisar."
    },
    "flexibleText": {
      "en": "Shape, stone, metal, scale",
      "ko": "형태, 스톤, 메탈, 크기",
      "zh": "造型、宝石、金属、比例",
      "es": "Forma, piedra, metal, escala"
    },
    "beforeProductionText": {
      "en": "Quote and CAD approval",
      "ko": "견적 및 CAD 승인",
      "zh": "报价与 CAD 确认",
      "es": "Cotización y aprobación CAD"
    }
  },
  {
    "id": "RING-022",
    "category": "ring",
    "subcategory": "weddingBand",
    "coverImage": "/assets/designs/BNGTXR00883-WG-RB-WH-100-M0-new.jpg",
    "media": [
      {
        "kind": "image",
        "src": "/assets/designs/BNGTXR00883-WG-RB-WH-100-M0-new.jpg"
      }
    ],
    "mediaComplete": true,
    "metalOptions": [
      "18kw",
      "18ky",
      "18kr",
      "pt"
    ],
    "estWeightG": 4.2,
    "laborUsd": 95,
    "leadDays": 12,
    "availableForSale": true,
    "published": true,
    "supplierEvidence": "https://www.grownbrilliance.com/1-ctw-round-lab-grown-diamond-eternity-band-platinum/pid/BNGTXR00883-900PL2?algoliaQueryId=99a64bb32066eda75e81b0f1e139dbb1",
    "firstQuoteAt": "2026-06-27",
    "name": {
      "en": "French Pavé Eternity Band",
      "ko": "프렌치 파베 이터니티 밴드",
      "zh": "法式密钉永恒戒圈",
      "es": "Banda eternity pavé francés"
    },
    "detailLabel": {
      "en": "Custom starter design",
      "ko": "맞춤 시작 디자인",
      "zh": "定制起点设计",
      "es": "Diseño inicial personalizado"
    },
    "description": {
      "en": "This is a sample starting point, not a limit. Share references and we can adjust shape, scale, stones, metal, and finish after review.",
      "ko": "이 디자인은 제한이 아니라 시작점입니다. 원하는 레퍼런스를 보내주시면 형태, 크기, 스톤, 메탈, 마감을 검토 후 조정할 수 있습니다.",
      "zh": "这是起点样例，不是限制。上传参考后，我们可评估并调整造型、尺寸、宝石、金属与细节。",
      "es": "Este diseño es un punto de partida, no un límite. Comparte referencias y ajustamos forma, escala, piedras, metal y acabado tras revisar."
    },
    "flexibleText": {
      "en": "Shape, stone, metal, scale",
      "ko": "형태, 스톤, 메탈, 크기",
      "zh": "造型、宝石、金属、比例",
      "es": "Forma, piedra, metal, escala"
    },
    "beforeProductionText": {
      "en": "Quote and CAD approval",
      "ko": "견적 및 CAD 승인",
      "zh": "报价与 CAD 确认",
      "es": "Cotización y aprobación CAD"
    }
  },
  {
    "id": "RING-023",
    "category": "ring",
    "subcategory": "weddingBand",
    "coverImage": "/assets/designs/RIGWR4428-WG-RB-WH-500-M0-new.jpg",
    "media": [
      {
        "kind": "image",
        "src": "/assets/designs/RIGWR4428-WG-RB-WH-500-M0-new.jpg"
      },
      {
        "kind": "image",
        "src": "/assets/designs/RIGWR4428-WG-RB-WH-500-M1-new.jpg"
      },
      {
        "kind": "image",
        "src": "/assets/designs/BNGWR4428-400GW4-1.jpg"
      }
    ],
    "mediaComplete": true,
    "metalOptions": [
      "18kw",
      "18ky",
      "18kr",
      "pt"
    ],
    "estWeightG": 4.2,
    "laborUsd": 95,
    "leadDays": 12,
    "availableForSale": true,
    "published": true,
    "supplierEvidence": "https://www.grownbrilliance.com/5-ctw-shared-prong-round-lab-grown-diamond-eternity-band-14k-white-gold/pid/BNGWR4428-700GW2",
    "firstQuoteAt": "2026-06-27",
    "name": {
      "en": "Low Dome Basket Eternity Band",
      "ko": "로우 돔 바스켓 이터니티 밴드",
      "zh": "低圆顶篮式永恒戒圈",
      "es": "Banda eternity basket domo bajo"
    },
    "detailLabel": {
      "en": "Custom starter design",
      "ko": "맞춤 시작 디자인",
      "zh": "定制起点设计",
      "es": "Diseño inicial personalizado"
    },
    "description": {
      "en": "This is a sample starting point, not a limit. Share references and we can adjust shape, scale, stones, metal, and finish after review.",
      "ko": "이 디자인은 제한이 아니라 시작점입니다. 원하는 레퍼런스를 보내주시면 형태, 크기, 스톤, 메탈, 마감을 검토 후 조정할 수 있습니다.",
      "zh": "这是起点样例，不是限制。上传参考后，我们可评估并调整造型、尺寸、宝石、金属与细节。",
      "es": "Este diseño es un punto de partida, no un límite. Comparte referencias y ajustamos forma, escala, piedras, metal y acabado tras revisar."
    },
    "flexibleText": {
      "en": "Shape, stone, metal, scale",
      "ko": "형태, 스톤, 메탈, 크기",
      "zh": "造型、宝石、金属、比例",
      "es": "Forma, piedra, metal, escala"
    },
    "beforeProductionText": {
      "en": "Quote and CAD approval",
      "ko": "견적 및 CAD 승인",
      "zh": "报价与 CAD 确认",
      "es": "Cotización y aprobación CAD"
    }
  },
  {
    "id": "RING-024",
    "category": "ring",
    "subcategory": "weddingBand",
    "coverImage": "/assets/designs/BNG341590-WG-RB-WH-300-M0-new.jpg",
    "media": [
      {
        "kind": "image",
        "src": "/assets/designs/BNG341590-WG-RB-WH-300-M0-new.jpg"
      }
    ],
    "mediaComplete": true,
    "metalOptions": [
      "18kw",
      "18ky",
      "18kr",
      "pt"
    ],
    "estWeightG": 4.2,
    "laborUsd": 95,
    "leadDays": 12,
    "availableForSale": true,
    "published": true,
    "supplierEvidence": "http://grownbrilliance.com/3-ctw-domed-round-lab-grown-diamond-eternity-band-platinum/pid/BNG341590-7.00PL4?algoliaQueryId=12aa90d075aa1c41db3733f84b4379fe",
    "firstQuoteAt": "2026-06-27",
    "name": {
      "en": "Pavé Band",
      "ko": "파베 밴드",
      "zh": "密钉戒圈",
      "es": "Banda pavé"
    },
    "detailLabel": {
      "en": "Custom starter design",
      "ko": "맞춤 시작 디자인",
      "zh": "定制起点设计",
      "es": "Diseño inicial personalizado"
    },
    "description": {
      "en": "This is a sample starting point, not a limit. Share references and we can adjust shape, scale, stones, metal, and finish after review.",
      "ko": "이 디자인은 제한이 아니라 시작점입니다. 원하는 레퍼런스를 보내주시면 형태, 크기, 스톤, 메탈, 마감을 검토 후 조정할 수 있습니다.",
      "zh": "这是起点样例，不是限制。上传参考后，我们可评估并调整造型、尺寸、宝石、金属与细节。",
      "es": "Este diseño es un punto de partida, no un límite. Comparte referencias y ajustamos forma, escala, piedras, metal y acabado tras revisar."
    },
    "flexibleText": {
      "en": "Shape, stone, metal, scale",
      "ko": "형태, 스톤, 메탈, 크기",
      "zh": "造型、宝石、金属、比例",
      "es": "Forma, piedra, metal, escala"
    },
    "beforeProductionText": {
      "en": "Quote and CAD approval",
      "ko": "견적 및 CAD 승인",
      "zh": "报价与 CAD 确认",
      "es": "Cotización y aprobación CAD"
    }
  },
  {
    "id": "RING-025",
    "category": "ring",
    "subcategory": "weddingBand",
    "coverImage": "/assets/designs/BNGYR1450K-WG-RB-WH-200-M0-new.jpg",
    "media": [
      {
        "kind": "image",
        "src": "/assets/designs/BNGYR1450K-WG-RB-WH-200-M0-new.jpg"
      },
      {
        "kind": "image",
        "src": "/assets/designs/BNGYR1450K-WG-RB-WH-200-M1-new.jpg"
      },
      {
        "kind": "image",
        "src": "/assets/designs/BNGYR1450F-GW4_-_BNGYR1450G-GW4_-_BNGYR1450K-GW4_-_BNGYR1450M-GW4_E_new.jpg"
      }
    ],
    "mediaComplete": true,
    "metalOptions": [
      "18kw",
      "18ky",
      "18kr",
      "pt"
    ],
    "estWeightG": 4.2,
    "laborUsd": 95,
    "leadDays": 12,
    "availableForSale": true,
    "published": true,
    "supplierEvidence": "https://www.grownbrilliance.com/2-ctw-round-lab-grown-diamond-channel-set-eternity-band-platinum/pid/BNGYR1450K-PL2-700",
    "firstQuoteAt": "2026-06-27",
    "name": {
      "en": "Channel Set Band",
      "ko": "채널 세트 밴드",
      "zh": "槽镶戒圈",
      "es": "Banda channel set"
    },
    "detailLabel": {
      "en": "Custom starter design",
      "ko": "맞춤 시작 디자인",
      "zh": "定制起点设计",
      "es": "Diseño inicial personalizado"
    },
    "description": {
      "en": "This is a sample starting point, not a limit. Share references and we can adjust shape, scale, stones, metal, and finish after review.",
      "ko": "이 디자인은 제한이 아니라 시작점입니다. 원하는 레퍼런스를 보내주시면 형태, 크기, 스톤, 메탈, 마감을 검토 후 조정할 수 있습니다.",
      "zh": "这是起点样例，不是限制。上传参考后，我们可评估并调整造型、尺寸、宝石、金属与细节。",
      "es": "Este diseño es un punto de partida, no un límite. Comparte referencias y ajustamos forma, escala, piedras, metal y acabado tras revisar."
    },
    "flexibleText": {
      "en": "Shape, stone, metal, scale",
      "ko": "형태, 스톤, 메탈, 크기",
      "zh": "造型、宝石、金属、比例",
      "es": "Forma, piedra, metal, escala"
    },
    "beforeProductionText": {
      "en": "Quote and CAD approval",
      "ko": "견적 및 CAD 승인",
      "zh": "报价与 CAD 确认",
      "es": "Cotización y aprobación CAD"
    }
  },
  {
    "id": "EARR-001",
    "category": "earrings",
    "subcategory": "studs",
    "coverImage": "/assets/designs/EAGTXE01900-GW3-1.jpg",
    "media": [
      {
        "kind": "image",
        "src": "/assets/designs/EAGTXE01900-GW3-1.jpg"
      },
      {
        "kind": "image",
        "src": "/assets/designs/EAGTXE01900-WG-RB-WH-150-M1-1.jpg"
      }
    ],
    "mediaComplete": true,
    "metalOptions": [
      "14kw",
      "14ky",
      "14kr",
      "18kw",
      "18ky"
    ],
    "estWeightG": 2.4,
    "laborUsd": 80,
    "leadDays": 10,
    "availableForSale": true,
    "published": true,
    "supplierEvidence": "https://www.grownbrilliance.com/1-1-2-ctw-round-lab-grown-diamond-stud-earrings-14k-white-gold/pid/EAGTXE01900-GW3",
    "firstQuoteAt": "2026-06-27",
    "name": {
      "en": "Round Diamond Stud Earrings",
      "ko": "라운드 다이아몬드 스터드 이어링",
      "zh": "圆形钻石耳钉",
      "es": "Aretes de diamantes redondos"
    },
    "detailLabel": {
      "en": "Custom starter design",
      "ko": "맞춤 시작 디자인",
      "zh": "定制起点设计",
      "es": "Diseño inicial personalizado"
    },
    "description": {
      "en": "This is a sample starting point, not a limit. Share references and we can adjust shape, scale, stones, metal, and finish after review.",
      "ko": "이 디자인은 제한이 아니라 시작점입니다. 원하는 레퍼런스를 보내주시면 형태, 크기, 스톤, 메탈, 마감을 검토 후 조정할 수 있습니다.",
      "zh": "这是起点样例，不是限制。上传参考后，我们可评估并调整造型、尺寸、宝石、金属与细节。",
      "es": "Este diseño es un punto de partida, no un límite. Comparte referencias y ajustamos forma, escala, piedras, metal y acabado tras revisar."
    },
    "flexibleText": {
      "en": "Pairing, post, drop length",
      "ko": "페어링, 포스트, 드롭 길이",
      "zh": "配对、耳针、垂坠长度",
      "es": "Par, poste, largo de caída"
    },
    "beforeProductionText": {
      "en": "Quote and CAD approval",
      "ko": "견적 및 CAD 승인",
      "zh": "报价与 CAD 确认",
      "es": "Cotización y aprobación CAD"
    }
  },
  {
    "id": "EARR-002",
    "category": "earrings",
    "subcategory": "huggies",
    "coverImage": "/assets/designs/EAGJOE555-GP2-1.jpg",
    "media": [
      {
        "kind": "image",
        "src": "/assets/designs/EAGJOE555-GP2-1.jpg"
      },
      {
        "kind": "image",
        "src": "/assets/designs/EAGJOE555-GP2-2.jpg"
      }
    ],
    "mediaComplete": true,
    "metalOptions": [
      "14kw",
      "14ky",
      "14kr",
      "18kw",
      "18ky"
    ],
    "estWeightG": 2.4,
    "laborUsd": 80,
    "leadDays": 10,
    "availableForSale": true,
    "published": true,
    "supplierEvidence": "https://www.grownbrilliance.com/4-ctw-round-lab-grown-diamond-inside-out-hoop-earrings-14k-rose-gold/pid/EAGJOE555-GP2",
    "firstQuoteAt": "2026-06-27",
    "name": {
      "en": "Inside-Out Hoop Earrings",
      "ko": "인사이드 아웃 후프 이어링",
      "zh": "内外镶钻圈形耳环",
      "es": "Aros inside-out"
    },
    "detailLabel": {
      "en": "Custom starter design",
      "ko": "맞춤 시작 디자인",
      "zh": "定制起点设计",
      "es": "Diseño inicial personalizado"
    },
    "description": {
      "en": "This is a sample starting point, not a limit. Share references and we can adjust shape, scale, stones, metal, and finish after review.",
      "ko": "이 디자인은 제한이 아니라 시작점입니다. 원하는 레퍼런스를 보내주시면 형태, 크기, 스톤, 메탈, 마감을 검토 후 조정할 수 있습니다.",
      "zh": "这是起点样例，不是限制。上传参考后，我们可评估并调整造型、尺寸、宝石、金属与细节。",
      "es": "Este diseño es un punto de partida, no un límite. Comparte referencias y ajustamos forma, escala, piedras, metal y acabado tras revisar."
    },
    "flexibleText": {
      "en": "Pairing, post, drop length",
      "ko": "페어링, 포스트, 드롭 길이",
      "zh": "配对、耳针、垂坠长度",
      "es": "Par, poste, largo de caída"
    },
    "beforeProductionText": {
      "en": "Quote and CAD approval",
      "ko": "견적 및 CAD 승인",
      "zh": "报价与 CAD 确认",
      "es": "Cotización y aprobación CAD"
    }
  },
  {
    "id": "EARR-003",
    "category": "earrings",
    "subcategory": "studs",
    "coverImage": "/assets/designs/EAGTXE02393-RG-PR-WH-119-M3.jpg",
    "media": [
      {
        "kind": "image",
        "src": "/assets/designs/EAGTXE02393-RG-PR-WH-119-M3.jpg"
      },
      {
        "kind": "image",
        "src": "/assets/designs/EAGTXE02393-RG-PR-WH-119-M1.jpg"
      },
      {
        "kind": "image",
        "src": "/assets/designs/TXE02393-1-GW1.jpg"
      }
    ],
    "mediaComplete": true,
    "metalOptions": [
      "14kw",
      "14ky",
      "14kr",
      "18kw",
      "18ky"
    ],
    "estWeightG": 2.4,
    "laborUsd": 80,
    "leadDays": 10,
    "availableForSale": true,
    "published": true,
    "supplierEvidence": "https://www.grownbrilliance.com/1-1-5-ctw-princess-lab-grown-diamond-halo-stud-earrings-14k-white-gold/pid/EAGTXE02393-GW3?category_id=49",
    "firstQuoteAt": "2026-06-27",
    "name": {
      "en": "Princess Halo Stud Earrings",
      "ko": "프린세스 헤일로 스터드 이어링",
      "zh": "公主方光环耳钉",
      "es": "Aretes halo princess"
    },
    "detailLabel": {
      "en": "Custom starter design",
      "ko": "맞춤 시작 디자인",
      "zh": "定制起点设计",
      "es": "Diseño inicial personalizado"
    },
    "description": {
      "en": "This is a sample starting point, not a limit. Share references and we can adjust shape, scale, stones, metal, and finish after review.",
      "ko": "이 디자인은 제한이 아니라 시작점입니다. 원하는 레퍼런스를 보내주시면 형태, 크기, 스톤, 메탈, 마감을 검토 후 조정할 수 있습니다.",
      "zh": "这是起点样例，不是限制。上传参考后，我们可评估并调整造型、尺寸、宝石、金属与细节。",
      "es": "Este diseño es un punto de partida, no un límite. Comparte referencias y ajustamos forma, escala, piedras, metal y acabado tras revisar."
    },
    "flexibleText": {
      "en": "Pairing, post, drop length",
      "ko": "페어링, 포스트, 드롭 길이",
      "zh": "配对、耳针、垂坠长度",
      "es": "Par, poste, largo de caída"
    },
    "beforeProductionText": {
      "en": "Quote and CAD approval",
      "ko": "견적 및 CAD 승인",
      "zh": "报价与 CAD 确认",
      "es": "Cotización y aprobación CAD"
    }
  },
  {
    "id": "EARR-004",
    "category": "earrings",
    "subcategory": "huggies",
    "coverImage": "/assets/designs/AJE06021-WG-M0.jpg",
    "media": [
      {
        "kind": "image",
        "src": "/assets/designs/AJE06021-WG-M0.jpg"
      },
      {
        "kind": "image",
        "src": "/assets/designs/AJE06021-WG-M1.jpg"
      }
    ],
    "mediaComplete": true,
    "metalOptions": [
      "14kw",
      "14ky",
      "14kr",
      "18kw",
      "18ky"
    ],
    "estWeightG": 2.4,
    "laborUsd": 80,
    "leadDays": 10,
    "availableForSale": true,
    "published": true,
    "supplierEvidence": "https://www.grownbrilliance.com/3-ctw-cushion-lab-grown-diamond-huggie-hoop-earrings-platinum/pid/EAGAJE06021-PL2",
    "firstQuoteAt": "2026-06-27",
    "name": {
      "en": "Cushion Huggie Hoop Earrings",
      "ko": "쿠션 허기 후프 이어링",
      "zh": "垫形贴耳圈耳环",
      "es": "Aros huggie cushion"
    },
    "detailLabel": {
      "en": "Custom starter design",
      "ko": "맞춤 시작 디자인",
      "zh": "定制起点设计",
      "es": "Diseño inicial personalizado"
    },
    "description": {
      "en": "This is a sample starting point, not a limit. Share references and we can adjust shape, scale, stones, metal, and finish after review.",
      "ko": "이 디자인은 제한이 아니라 시작점입니다. 원하는 레퍼런스를 보내주시면 형태, 크기, 스톤, 메탈, 마감을 검토 후 조정할 수 있습니다.",
      "zh": "这是起点样例，不是限制。上传参考后，我们可评估并调整造型、尺寸、宝石、金属与细节。",
      "es": "Este diseño es un punto de partida, no un límite. Comparte referencias y ajustamos forma, escala, piedras, metal y acabado tras revisar."
    },
    "flexibleText": {
      "en": "Pairing, post, drop length",
      "ko": "페어링, 포스트, 드롭 길이",
      "zh": "配对、耳针、垂坠长度",
      "es": "Par, poste, largo de caída"
    },
    "beforeProductionText": {
      "en": "Quote and CAD approval",
      "ko": "견적 및 CAD 승인",
      "zh": "报价与 CAD 确认",
      "es": "Cotización y aprobación CAD"
    }
  },
  {
    "id": "EARR-005",
    "category": "earrings",
    "subcategory": "drops",
    "coverImage": "/assets/designs/EAGTXE02083-RG-EM-WH-250-M0.jpg",
    "media": [
      {
        "kind": "image",
        "src": "/assets/designs/EAGTXE02083-RG-EM-WH-250-M0.jpg"
      },
      {
        "kind": "image",
        "src": "/assets/designs/EAGTXE02083-RG-EM-WH-250-M1.jpg"
      }
    ],
    "mediaComplete": true,
    "metalOptions": [
      "14kw",
      "14ky",
      "14kr",
      "18kw",
      "18ky"
    ],
    "estWeightG": 2.4,
    "laborUsd": 80,
    "leadDays": 10,
    "availableForSale": true,
    "published": true,
    "supplierEvidence": "https://www.grownbrilliance.com/3-1-2-ctw-emerald-lab-grown-diamond-halo-drop-earrings-14k-rose-gold/pid/EAGTXE02084-GP2",
    "firstQuoteAt": "2026-06-27",
    "name": {
      "en": "Emerald Halo Drop Earrings",
      "ko": "에메랄드 헤일로 드롭 이어링",
      "zh": "祖母绿形光环垂坠耳环",
      "es": "Aretes colgantes halo esmeralda"
    },
    "detailLabel": {
      "en": "Custom starter design",
      "ko": "맞춤 시작 디자인",
      "zh": "定制起点设计",
      "es": "Diseño inicial personalizado"
    },
    "description": {
      "en": "This is a sample starting point, not a limit. Share references and we can adjust shape, scale, stones, metal, and finish after review.",
      "ko": "이 디자인은 제한이 아니라 시작점입니다. 원하는 레퍼런스를 보내주시면 형태, 크기, 스톤, 메탈, 마감을 검토 후 조정할 수 있습니다.",
      "zh": "这是起点样例，不是限制。上传参考后，我们可评估并调整造型、尺寸、宝石、金属与细节。",
      "es": "Este diseño es un punto de partida, no un límite. Comparte referencias y ajustamos forma, escala, piedras, metal y acabado tras revisar."
    },
    "flexibleText": {
      "en": "Pairing, post, drop length",
      "ko": "페어링, 포스트, 드롭 길이",
      "zh": "配对、耳针、垂坠长度",
      "es": "Par, poste, largo de caída"
    },
    "beforeProductionText": {
      "en": "Quote and CAD approval",
      "ko": "견적 및 CAD 승인",
      "zh": "报价与 CAD 确认",
      "es": "Cotización y aprobación CAD"
    }
  },
  {
    "id": "EARR-006",
    "category": "earrings",
    "subcategory": "drops",
    "coverImage": "/assets/designs/AJE09546-WG-M0.jpg",
    "media": [
      {
        "kind": "image",
        "src": "/assets/designs/AJE09546-WG-M0.jpg"
      }
    ],
    "mediaComplete": true,
    "metalOptions": [
      "14kw",
      "14ky",
      "14kr",
      "18kw",
      "18ky"
    ],
    "estWeightG": 2.4,
    "laborUsd": 80,
    "leadDays": 10,
    "availableForSale": true,
    "published": true,
    "supplierEvidence": "https://www.grownbrilliance.com/4-ctw-pear-and-oval-lab-grown-diamond-drop-earrings-14k-white-gold/pid/EAGAJE09546-GW2?algoliaQueryId=ed74e9eebe06214cb2d30147f83e452d",
    "firstQuoteAt": "2026-06-27",
    "name": {
      "en": "Round and Pear Drop Earrings",
      "ko": "라운드 앤 페어 드롭 이어링",
      "zh": "圆形梨形垂坠耳环",
      "es": "Aretes colgantes redondo y pera"
    },
    "detailLabel": {
      "en": "Custom starter design",
      "ko": "맞춤 시작 디자인",
      "zh": "定制起点设计",
      "es": "Diseño inicial personalizado"
    },
    "description": {
      "en": "This is a sample starting point, not a limit. Share references and we can adjust shape, scale, stones, metal, and finish after review.",
      "ko": "이 디자인은 제한이 아니라 시작점입니다. 원하는 레퍼런스를 보내주시면 형태, 크기, 스톤, 메탈, 마감을 검토 후 조정할 수 있습니다.",
      "zh": "这是起点样例，不是限制。上传参考后，我们可评估并调整造型、尺寸、宝石、金属与细节。",
      "es": "Este diseño es un punto de partida, no un límite. Comparte referencias y ajustamos forma, escala, piedras, metal y acabado tras revisar."
    },
    "flexibleText": {
      "en": "Pairing, post, drop length",
      "ko": "페어링, 포스트, 드롭 길이",
      "zh": "配对、耳针、垂坠长度",
      "es": "Par, poste, largo de caída"
    },
    "beforeProductionText": {
      "en": "Quote and CAD approval",
      "ko": "견적 및 CAD 승인",
      "zh": "报价与 CAD 确认",
      "es": "Cotización y aprobación CAD"
    }
  },
  {
    "id": "EARR-007",
    "category": "earrings",
    "subcategory": "studs",
    "coverImage": "/assets/designs/AJE00461-WG-M0_.jpg",
    "media": [
      {
        "kind": "image",
        "src": "/assets/designs/AJE00461-WG-M0_.jpg"
      }
    ],
    "mediaComplete": true,
    "metalOptions": [
      "14kw",
      "14ky",
      "14kr",
      "18kw",
      "18ky"
    ],
    "estWeightG": 2.4,
    "laborUsd": 80,
    "leadDays": 10,
    "availableForSale": true,
    "published": true,
    "supplierEvidence": "https://www.grownbrilliance.com/1-1-2-ctw-marquise-lab-grown-diamond-flower-stud-earrings-platinum/pid/EAGAJE00896TC-GW4?customQueryId=q1783923746541oqyl8sck2&category_id=35",
    "firstQuoteAt": "2026-06-27",
    "name": {
      "en": "Marquise Flower Stud Earrings",
      "ko": "마퀴즈 플라워 스터드 이어링",
      "zh": "马眼形花朵耳钉",
      "es": "Aretes flor marquise"
    },
    "detailLabel": {
      "en": "Custom starter design",
      "ko": "맞춤 시작 디자인",
      "zh": "定制起点设计",
      "es": "Diseño inicial personalizado"
    },
    "description": {
      "en": "This is a sample starting point, not a limit. Share references and we can adjust shape, scale, stones, metal, and finish after review.",
      "ko": "이 디자인은 제한이 아니라 시작점입니다. 원하는 레퍼런스를 보내주시면 형태, 크기, 스톤, 메탈, 마감을 검토 후 조정할 수 있습니다.",
      "zh": "这是起点样例，不是限制。上传参考后，我们可评估并调整造型、尺寸、宝石、金属与细节。",
      "es": "Este diseño es un punto de partida, no un límite. Comparte referencias y ajustamos forma, escala, piedras, metal y acabado tras revisar."
    },
    "flexibleText": {
      "en": "Pairing, post, drop length",
      "ko": "페어링, 포스트, 드롭 길이",
      "zh": "配对、耳针、垂坠长度",
      "es": "Par, poste, largo de caída"
    },
    "beforeProductionText": {
      "en": "Quote and CAD approval",
      "ko": "견적 및 CAD 승인",
      "zh": "报价与 CAD 确认",
      "es": "Cotización y aprobación CAD"
    }
  },
  {
    "id": "BRAC-001",
    "category": "bangle",
    "subcategory": "tennisBracelet",
    "coverImage": "/assets/designs/BCGTXBR00769-WG-RB-WH-1200-M0.jpg",
    "media": [
      {
        "kind": "image",
        "src": "/assets/designs/BCGTXBR00769-WG-RB-WH-1200-M0.jpg"
      }
    ],
    "mediaComplete": true,
    "metalOptions": [
      "14kw",
      "14ky",
      "18kw",
      "18ky"
    ],
    "estWeightG": 9.6,
    "laborUsd": 170,
    "leadDays": 16,
    "availableForSale": true,
    "published": true,
    "supplierEvidence": "https://www.grownbrilliance.com/12-ctw-round-lab-grown-diamond-four-prong-tennis-bracelet-14k-platinum-7-5-inches/pid/BCGTXBR00769-PL2?category_id=112",
    "firstQuoteAt": "2026-06-27",
    "name": {
      "en": "Four-Prong Tennis Bracelet",
      "ko": "4프롱 테니스 브레이슬릿",
      "zh": "四爪网球手链",
      "es": "Pulsera tenis de 4 garras"
    },
    "detailLabel": {
      "en": "Custom starter design",
      "ko": "맞춤 시작 디자인",
      "zh": "定制起点设计",
      "es": "Diseño inicial personalizado"
    },
    "description": {
      "en": "This is a sample starting point, not a limit. Share references and we can adjust shape, scale, stones, metal, and finish after review.",
      "ko": "이 디자인은 제한이 아니라 시작점입니다. 원하는 레퍼런스를 보내주시면 형태, 크기, 스톤, 메탈, 마감을 검토 후 조정할 수 있습니다.",
      "zh": "这是起点样例，不是限制。上传参考后，我们可评估并调整造型、尺寸、宝石、金属与细节。",
      "es": "Este diseño es un punto de partida, no un límite. Comparte referencias y ajustamos forma, escala, piedras, metal y acabado tras revisar."
    },
    "flexibleText": {
      "en": "Length, clasp, stone size",
      "ko": "길이, 잠금장식, 스톤 크기",
      "zh": "长度、扣件、宝石尺寸",
      "es": "Largo, broche, tamaño de piedra"
    },
    "beforeProductionText": {
      "en": "Quote and CAD approval",
      "ko": "견적 및 CAD 승인",
      "zh": "报价与 CAD 确认",
      "es": "Cotización y aprobación CAD"
    }
  },
  {
    "id": "BRAC-002",
    "category": "bangle",
    "subcategory": "tennisBracelet",
    "coverImage": "/assets/designs/BRAAAB02136V-WG-RB-446-M0-1.jpg",
    "media": [
      {
        "kind": "image",
        "src": "/assets/designs/BRAAAB02136V-WG-RB-446-M0-1.jpg"
      }
    ],
    "mediaComplete": true,
    "metalOptions": [
      "14kw",
      "14ky",
      "18kw",
      "18ky"
    ],
    "estWeightG": 9.6,
    "laborUsd": 170,
    "leadDays": 16,
    "availableForSale": true,
    "published": true,
    "supplierEvidence": "https://www.grownbrilliance.com/boundless-eternity-bracelet-14k-white-gold-7-inches/pid/BOBRA02136VGW2-7.0?customQueryId=q17839229609208h2q9etkj&category_id=67",
    "firstQuoteAt": "2026-06-27",
    "name": {
      "en": "Boundless Eternity Bracelet",
      "ko": "바운드리스 이터니티 브레이슬릿",
      "zh": "无界永恒手链",
      "es": "Pulsera eternity boundless"
    },
    "detailLabel": {
      "en": "Custom starter design",
      "ko": "맞춤 시작 디자인",
      "zh": "定制起点设计",
      "es": "Diseño inicial personalizado"
    },
    "description": {
      "en": "This is a sample starting point, not a limit. Share references and we can adjust shape, scale, stones, metal, and finish after review.",
      "ko": "이 디자인은 제한이 아니라 시작점입니다. 원하는 레퍼런스를 보내주시면 형태, 크기, 스톤, 메탈, 마감을 검토 후 조정할 수 있습니다.",
      "zh": "这是起点样例，不是限制。上传参考后，我们可评估并调整造型、尺寸、宝石、金属与细节。",
      "es": "Este diseño es un punto de partida, no un límite. Comparte referencias y ajustamos forma, escala, piedras, metal y acabado tras revisar."
    },
    "flexibleText": {
      "en": "Length, clasp, stone size",
      "ko": "길이, 잠금장식, 스톤 크기",
      "zh": "长度、扣件、宝石尺寸",
      "es": "Largo, broche, tamaño de piedra"
    },
    "beforeProductionText": {
      "en": "Quote and CAD approval",
      "ko": "견적 및 CAD 승인",
      "zh": "报价与 CAD 确认",
      "es": "Cotización y aprobación CAD"
    }
  },
  {
    "id": "BRAC-003",
    "category": "bangle",
    "subcategory": "tennisBracelet",
    "coverImage": "/assets/designs/BCGTXBR01703-WG-EM-WH-700-M0.jpg",
    "media": [
      {
        "kind": "image",
        "src": "/assets/designs/BCGTXBR01703-WG-EM-WH-700-M0.jpg"
      }
    ],
    "mediaComplete": true,
    "metalOptions": [
      "14kw",
      "14ky",
      "18kw",
      "18ky"
    ],
    "estWeightG": 9.6,
    "laborUsd": 170,
    "leadDays": 16,
    "availableForSale": true,
    "published": true,
    "supplierEvidence": "https://www.grownbrilliance.com/5-ctw-emerald-lab-grown-diamond-tennis-bracelet-14k-white-gold-7-5-inches/pid/BCTXBR01703-5GW270?customQueryId=q178392307649715od03rfv",
    "firstQuoteAt": "2026-06-27",
    "name": {
      "en": "Emerald Tennis Bracelet",
      "ko": "에메랄드 테니스 브레이슬릿",
      "zh": "祖母绿网球手链",
      "es": "Pulsera tenis esmeralda"
    },
    "detailLabel": {
      "en": "Custom starter design",
      "ko": "맞춤 시작 디자인",
      "zh": "定制起点设计",
      "es": "Diseño inicial personalizado"
    },
    "description": {
      "en": "This is a sample starting point, not a limit. Share references and we can adjust shape, scale, stones, metal, and finish after review.",
      "ko": "이 디자인은 제한이 아니라 시작점입니다. 원하는 레퍼런스를 보내주시면 형태, 크기, 스톤, 메탈, 마감을 검토 후 조정할 수 있습니다.",
      "zh": "这是起点样例，不是限制。上传参考后，我们可评估并调整造型、尺寸、宝石、金属与细节。",
      "es": "Este diseño es un punto de partida, no un límite. Comparte referencias y ajustamos forma, escala, piedras, metal y acabado tras revisar."
    },
    "flexibleText": {
      "en": "Length, clasp, stone size",
      "ko": "길이, 잠금장식, 스톤 크기",
      "zh": "长度、扣件、宝石尺寸",
      "es": "Largo, broche, tamaño de piedra"
    },
    "beforeProductionText": {
      "en": "Quote and CAD approval",
      "ko": "견적 및 CAD 승인",
      "zh": "报价与 CAD 确认",
      "es": "Cotización y aprobación CAD"
    }
  },
  {
    "id": "BRAC-004",
    "category": "bangle",
    "subcategory": "bangle",
    "coverImage": "/assets/designs/BCGVG2664K-WG-RB-WH-210-M0.jpg",
    "media": [
      {
        "kind": "image",
        "src": "/assets/designs/BCGVG2664K-WG-RB-WH-210-M0.jpg"
      },
      {
        "kind": "image",
        "src": "/assets/designs/BCGVG2664K-WG-RB-WH-210-M3.jpg"
      },
      {
        "kind": "image",
        "src": "/assets/designs/BCGVG2664K-GW4-1_new.jpg"
      },
      {
        "kind": "image",
        "src": "/assets/designs/BCGVG2664K-WG-M2.jpg"
      }
    ],
    "mediaComplete": true,
    "metalOptions": [
      "14kw",
      "14ky",
      "18kw",
      "18ky"
    ],
    "estWeightG": 9.6,
    "laborUsd": 170,
    "leadDays": 16,
    "availableForSale": true,
    "published": true,
    "supplierEvidence": "https://www.grownbrilliance.com/2-ctw-round-lab-grown-diamond-shared-prongs-bangle-bracelet-14k-white-gold-7-inches/pid/BCGVG2664K-GW2",
    "firstQuoteAt": "2026-06-27",
    "name": {
      "en": "Shared-Prong Bangle Bracelet",
      "ko": "쉐어드 프롱 뱅글 브레이슬릿",
      "zh": "共爪手镯",
      "es": "Brazalete de garras compartidas"
    },
    "detailLabel": {
      "en": "Custom starter design",
      "ko": "맞춤 시작 디자인",
      "zh": "定制起点设计",
      "es": "Diseño inicial personalizado"
    },
    "description": {
      "en": "This is a sample starting point, not a limit. Share references and we can adjust shape, scale, stones, metal, and finish after review.",
      "ko": "이 디자인은 제한이 아니라 시작점입니다. 원하는 레퍼런스를 보내주시면 형태, 크기, 스톤, 메탈, 마감을 검토 후 조정할 수 있습니다.",
      "zh": "这是起点样例，不是限制。上传参考后，我们可评估并调整造型、尺寸、宝石、金属与细节。",
      "es": "Este diseño es un punto de partida, no un límite. Comparte referencias y ajustamos forma, escala, piedras, metal y acabado tras revisar."
    },
    "flexibleText": {
      "en": "Length, clasp, stone size",
      "ko": "길이, 잠금장식, 스톤 크기",
      "zh": "长度、扣件、宝石尺寸",
      "es": "Largo, broche, tamaño de piedra"
    },
    "beforeProductionText": {
      "en": "Quote and CAD approval",
      "ko": "견적 및 CAD 승인",
      "zh": "报价与 CAD 确认",
      "es": "Cotización y aprobación CAD"
    }
  },
  {
    "id": "BRAC-005",
    "category": "bangle",
    "subcategory": "chainBracelet",
    "coverImage": "/assets/designs/BRAAAB01755U-WG-RB-350-M0-1.jpg",
    "media": [
      {
        "kind": "image",
        "src": "/assets/designs/BRAAAB01755U-WG-RB-350-M0-1.jpg"
      }
    ],
    "mediaComplete": true,
    "metalOptions": [
      "14kw",
      "14ky",
      "18kw",
      "18ky"
    ],
    "estWeightG": 9.6,
    "laborUsd": 170,
    "leadDays": 16,
    "availableForSale": true,
    "published": true,
    "supplierEvidence": "https://www.grownbrilliance.com/boundless-station-bracelet-14k-white-gold-6-inches/pid/BOBRA01755UGW2-6.0?algoliaQueryId=0d19910ee1c6777c60cdf063b61b6342",
    "firstQuoteAt": "2026-06-27",
    "name": {
      "en": "Boundless Station Bracelet",
      "ko": "바운드리스 스테이션 브레이슬릿",
      "zh": "无界站点手链",
      "es": "Pulsera station boundless"
    },
    "detailLabel": {
      "en": "Custom starter design",
      "ko": "맞춤 시작 디자인",
      "zh": "定制起点设计",
      "es": "Diseño inicial personalizado"
    },
    "description": {
      "en": "This is a sample starting point, not a limit. Share references and we can adjust shape, scale, stones, metal, and finish after review.",
      "ko": "이 디자인은 제한이 아니라 시작점입니다. 원하는 레퍼런스를 보내주시면 형태, 크기, 스톤, 메탈, 마감을 검토 후 조정할 수 있습니다.",
      "zh": "这是起点样例，不是限制。上传参考后，我们可评估并调整造型、尺寸、宝石、金属与细节。",
      "es": "Este diseño es un punto de partida, no un límite. Comparte referencias y ajustamos forma, escala, piedras, metal y acabado tras revisar."
    },
    "flexibleText": {
      "en": "Length, clasp, stone size",
      "ko": "길이, 잠금장식, 스톤 크기",
      "zh": "长度、扣件、宝石尺寸",
      "es": "Largo, broche, tamaño de piedra"
    },
    "beforeProductionText": {
      "en": "Quote and CAD approval",
      "ko": "견적 및 CAD 승인",
      "zh": "报价与 CAD 确认",
      "es": "Cotización y aprobación CAD"
    }
  },
  {
    "id": "NECK-001",
    "category": "necklace",
    "subcategory": "pendant",
    "coverImage": "/assets/designs/PNGTXP07660R300-WG-RB-WH-300-M0.jpg",
    "media": [
      {
        "kind": "image",
        "src": "/assets/designs/PNGTXP07660R300-WG-RB-WH-300-M0.jpg"
      },
      {
        "kind": "image",
        "src": "/assets/designs/PNGTXP07660R300-WG-RB-WH-300-M1.jpg"
      },
      {
        "kind": "image",
        "src": "/assets/designs/PNGTXP07660R150-GW6-new.jpg"
      }
    ],
    "mediaComplete": true,
    "metalOptions": [
      "14kw",
      "14ky",
      "18kw",
      "18ky",
      "pt"
    ],
    "estWeightG": 4.2,
    "laborUsd": 85,
    "leadDays": 12,
    "availableForSale": true,
    "published": true,
    "supplierEvidence": "https://www.grownbrilliance.com/3-ctw-round-lab-grown-diamond-solitaire-pendant-platinum/pid/PNGTXP07660R300-PL3",
    "firstQuoteAt": "2026-06-27",
    "name": {
      "en": "Round Solitaire Pendant",
      "ko": "라운드 솔리테어 펜던트",
      "zh": "圆形单钻吊坠",
      "es": "Colgante solitario redondo"
    },
    "detailLabel": {
      "en": "Custom starter design",
      "ko": "맞춤 시작 디자인",
      "zh": "定制起点设计",
      "es": "Diseño inicial personalizado"
    },
    "description": {
      "en": "This is a sample starting point, not a limit. Share references and we can adjust shape, scale, stones, metal, and finish after review.",
      "ko": "이 디자인은 제한이 아니라 시작점입니다. 원하는 레퍼런스를 보내주시면 형태, 크기, 스톤, 메탈, 마감을 검토 후 조정할 수 있습니다.",
      "zh": "这是起点样例，不是限制。上传参考后，我们可评估并调整造型、尺寸、宝石、金属与细节。",
      "es": "Este diseño es un punto de partida, no un límite. Comparte referencias y ajustamos forma, escala, piedras, metal y acabado tras revisar."
    },
    "flexibleText": {
      "en": "Chain, length, pendant scale",
      "ko": "체인, 길이, 펜던트 크기",
      "zh": "链型、长度、吊坠比例",
      "es": "Cadena, largo, escala del colgante"
    },
    "beforeProductionText": {
      "en": "Quote and CAD approval",
      "ko": "견적 및 CAD 승인",
      "zh": "报价与 CAD 确认",
      "es": "Cotización y aprobación CAD"
    }
  },
  {
    "id": "NECK-002",
    "category": "necklace",
    "subcategory": "pendant",
    "coverImage": "/assets/designs/PNGTXP01957-RG-RB-WH-175-M0.jpg",
    "media": [
      {
        "kind": "image",
        "src": "/assets/designs/PNGTXP01957-RG-RB-WH-175-M0.jpg"
      },
      {
        "kind": "image",
        "src": "/assets/designs/PNGTXP01957-RG-RB-WH-175-M1.jpg"
      },
      {
        "kind": "image",
        "src": "/assets/designs/PNGTXP01957-RG-M2.jpg"
      }
    ],
    "mediaComplete": true,
    "metalOptions": [
      "14kw",
      "14ky",
      "18kw",
      "18ky",
      "pt"
    ],
    "estWeightG": 4.2,
    "laborUsd": 85,
    "leadDays": 12,
    "availableForSale": true,
    "published": true,
    "supplierEvidence": "https://www.grownbrilliance.com/1-3-4-ctw-round-lab-grown-diamond-halo-pendant-with-adjustable-chain-14k-rose-gold/pid/PNGTXP01957-GP3",
    "firstQuoteAt": "2026-06-27",
    "name": {
      "en": "Round Halo Pendant",
      "ko": "라운드 헤일로 펜던트",
      "zh": "圆形光环吊坠",
      "es": "Colgante halo redondo"
    },
    "detailLabel": {
      "en": "Custom starter design",
      "ko": "맞춤 시작 디자인",
      "zh": "定制起点设计",
      "es": "Diseño inicial personalizado"
    },
    "description": {
      "en": "This is a sample starting point, not a limit. Share references and we can adjust shape, scale, stones, metal, and finish after review.",
      "ko": "이 디자인은 제한이 아니라 시작점입니다. 원하는 레퍼런스를 보내주시면 형태, 크기, 스톤, 메탈, 마감을 검토 후 조정할 수 있습니다.",
      "zh": "这是起点样例，不是限制。上传参考后，我们可评估并调整造型、尺寸、宝石、金属与细节。",
      "es": "Este diseño es un punto de partida, no un límite. Comparte referencias y ajustamos forma, escala, piedras, metal y acabado tras revisar."
    },
    "flexibleText": {
      "en": "Chain, length, pendant scale",
      "ko": "체인, 길이, 펜던트 크기",
      "zh": "链型、长度、吊坠比例",
      "es": "Cadena, largo, escala del colgante"
    },
    "beforeProductionText": {
      "en": "Quote and CAD approval",
      "ko": "견적 및 CAD 승인",
      "zh": "报价与 CAD 确认",
      "es": "Cotización y aprobación CAD"
    }
  },
  {
    "id": "NECK-003",
    "category": "necklace",
    "subcategory": "pendant",
    "coverImage": "/assets/designs/857162W1404L_SKU_1_1600X1600.jpg",
    "media": [
      {
        "kind": "image",
        "src": "/assets/designs/857162W1404L_SKU_1_1600X1600.jpg"
      }
    ],
    "mediaComplete": true,
    "metalOptions": [
      "14kw",
      "14ky",
      "18kw",
      "18ky",
      "pt"
    ],
    "estWeightG": 4.2,
    "laborUsd": 85,
    "leadDays": 12,
    "availableForSale": true,
    "published": true,
    "supplierEvidence": "https://www.bluenile.com/jewelry/necklaces/cluster-diamond-flower-pendant-necklace-with-1-ctw-round-cut-lab-grown-diamonds-in-14k-white-gold-item-302692?utm_source=google&utm_medium=sem_unbranded_shopping&utm_campaign=semus_bn_google_us_jewelry_labgrownjewelry&utm_term=Lab_Grown_Necklaces&utm_content=666911997034&gad_source=1&gad_campaignid=20393548284&gbraid=0AAAAAD_EjsilRPYWMzhiU0urRrZuL3i6o&gclid=Cj0KCQjwxvjRBhC2ARIsAI7KJa3t9XcuR6rpiNTADWTAxjq94mLctYRBBGG850eFFPj_QlzJYPnNi0UaAm2_EALw_wcB",
    "firstQuoteAt": "2026-06-27",
    "name": {
      "en": "Cluster Flower Pendant",
      "ko": "클러스터 플라워 펜던트",
      "zh": "簇镶花朵吊坠",
      "es": "Colgante floral cluster"
    },
    "detailLabel": {
      "en": "Custom starter design",
      "ko": "맞춤 시작 디자인",
      "zh": "定制起点设计",
      "es": "Diseño inicial personalizado"
    },
    "description": {
      "en": "This is a sample starting point, not a limit. Share references and we can adjust shape, scale, stones, metal, and finish after review.",
      "ko": "이 디자인은 제한이 아니라 시작점입니다. 원하는 레퍼런스를 보내주시면 형태, 크기, 스톤, 메탈, 마감을 검토 후 조정할 수 있습니다.",
      "zh": "这是起点样例，不是限制。上传参考后，我们可评估并调整造型、尺寸、宝石、金属与细节。",
      "es": "Este diseño es un punto de partida, no un límite. Comparte referencias y ajustamos forma, escala, piedras, metal y acabado tras revisar."
    },
    "flexibleText": {
      "en": "Chain, length, pendant scale",
      "ko": "체인, 길이, 펜던트 크기",
      "zh": "链型、长度、吊坠比例",
      "es": "Cadena, largo, escala del colgante"
    },
    "beforeProductionText": {
      "en": "Quote and CAD approval",
      "ko": "견적 및 CAD 승인",
      "zh": "报价与 CAD 确认",
      "es": "Cotización y aprobación CAD"
    }
  },
  {
    "id": "NECK-004",
    "category": "necklace",
    "subcategory": "stationNecklace",
    "coverImage": "/assets/designs/NCGRVN01233R500-WG-RB-WH-500-M0.jpg",
    "media": [
      {
        "kind": "image",
        "src": "/assets/designs/NCGRVN01233R500-WG-RB-WH-500-M0.jpg"
      }
    ],
    "mediaComplete": true,
    "metalOptions": [
      "14kw",
      "14ky",
      "18kw",
      "18ky",
      "pt"
    ],
    "estWeightG": 4.2,
    "laborUsd": 85,
    "leadDays": 12,
    "availableForSale": true,
    "published": true,
    "supplierEvidence": "https://www.grownbrilliance.com/5-ctw-round-lab-grown-diamond-thirteen-stone-demi-eternity-necklace-14k-white-gold/pid/NECRN01233R500-GW2?cq_src=google_ads&cq_cmp=22123575278&cq_con=178662484052&cq_term=&cq_med=pla&cq_plac=&cq_net=g&cq_plt=gp&gad_source=1&gad_campaignid=22123575278&gclid=Cj0KCQjwxvjRBhC2ARIsAI7KJa3vJ9HK-qt1-kNJTNygGs5lxu8oEQOPCPu8Oc0cUu9fngs0HkEYxvQaAovcEALw_wcB",
    "firstQuoteAt": "2026-06-27",
    "name": {
      "en": "Thirteen-Stone Demi Eternity Necklace",
      "ko": "13스톤 데미 이터니티 네크리스",
      "zh": "十三石半圈永恒项链",
      "es": "Collar demi eternity de trece piedras"
    },
    "detailLabel": {
      "en": "Custom starter design",
      "ko": "맞춤 시작 디자인",
      "zh": "定制起点设计",
      "es": "Diseño inicial personalizado"
    },
    "description": {
      "en": "This is a sample starting point, not a limit. Share references and we can adjust shape, scale, stones, metal, and finish after review.",
      "ko": "이 디자인은 제한이 아니라 시작점입니다. 원하는 레퍼런스를 보내주시면 형태, 크기, 스톤, 메탈, 마감을 검토 후 조정할 수 있습니다.",
      "zh": "这是起点样例，不是限制。上传参考后，我们可评估并调整造型、尺寸、宝石、金属与细节。",
      "es": "Este diseño es un punto de partida, no un límite. Comparte referencias y ajustamos forma, escala, piedras, metal y acabado tras revisar."
    },
    "flexibleText": {
      "en": "Chain, length, pendant scale",
      "ko": "체인, 길이, 펜던트 크기",
      "zh": "链型、长度、吊坠比例",
      "es": "Cadena, largo, escala del colgante"
    },
    "beforeProductionText": {
      "en": "Quote and CAD approval",
      "ko": "견적 및 CAD 승인",
      "zh": "报价与 CAD 确认",
      "es": "Cotización y aprobación CAD"
    }
  },
  {
    "id": "NECK-005",
    "category": "necklace",
    "subcategory": "pendant",
    "coverImage": "/assets/designs/857170W14L_SKU_1_1600X1600.jpg",
    "media": [
      {
        "kind": "image",
        "src": "/assets/designs/857170W14L_SKU_1_1600X1600.jpg"
      }
    ],
    "mediaComplete": true,
    "metalOptions": [
      "14kw",
      "14ky",
      "18kw",
      "18ky",
      "pt"
    ],
    "estWeightG": 4.2,
    "laborUsd": 85,
    "leadDays": 12,
    "availableForSale": true,
    "published": true,
    "supplierEvidence": "https://www.bluenile.com/jewelry/necklaces/diamond-drop-necklace-with-125-ctw-round-and-pear-shaped-lab-grown-diamonds-in-14k-white-gold-item-309201?utm_source=google&utm_medium=sem_unbranded_shopping&utm_campaign=semus_bn_google_us_jewelry_labgrownjewelry&utm_term=Lab_Grown_Necklaces&utm_content=666911997034&gad_source=1&gad_campaignid=20393548284&gbraid=0AAAAAD_EjsilRPYWMzhiU0urRrZuL3i6o&gclid=Cj0KCQjwxvjRBhC2ARIsAI7KJa2FQc5EygWIe3q_o3M75IZkmKuoouvPKLmjysKE8mvOPy7mqFJtvfEaAvbaEALw_wcB",
    "firstQuoteAt": "2026-06-27",
    "name": {
      "en": "Round and Pear Diamond Drop Necklace",
      "ko": "라운드 앤 페어 다이아 드롭 네크리스",
      "zh": "圆形与梨形钻石垂坠项链",
      "es": "Collar de diamantes redondo y pera"
    },
    "detailLabel": {
      "en": "Custom starter design",
      "ko": "맞춤 시작 디자인",
      "zh": "定制起点设计",
      "es": "Diseño inicial personalizado"
    },
    "description": {
      "en": "This is a sample starting point, not a limit. Share references and we can adjust shape, scale, stones, metal, and finish after review.",
      "ko": "이 디자인은 제한이 아니라 시작점입니다. 원하는 레퍼런스를 보내주시면 형태, 크기, 스톤, 메탈, 마감을 검토 후 조정할 수 있습니다.",
      "zh": "这是起点样例，不是限制。上传参考后，我们可评估并调整造型、尺寸、宝石、金属与细节。",
      "es": "Este diseño es un punto de partida, no un límite. Comparte referencias y ajustamos forma, escala, piedras, metal y acabado tras revisar."
    },
    "flexibleText": {
      "en": "Chain, length, pendant scale",
      "ko": "체인, 길이, 펜던트 크기",
      "zh": "链型、长度、吊坠比例",
      "es": "Cadena, largo, escala del colgante"
    },
    "beforeProductionText": {
      "en": "Quote and CAD approval",
      "ko": "견적 및 CAD 승인",
      "zh": "报价与 CAD 确认",
      "es": "Cotización y aprobación CAD"
    }
  },
  {
    "id": "NECK-006",
    "category": "necklace",
    "subcategory": "pendant",
    "coverImage": "/assets/designs/DP2284-2W_f45a16d1-c237-45c6-b77f-74978e8991c0.jpg",
    "media": [
      {
        "kind": "image",
        "src": "/assets/designs/DP2284-2W_f45a16d1-c237-45c6-b77f-74978e8991c0.jpg"
      }
    ],
    "mediaComplete": true,
    "metalOptions": [
      "14kw",
      "14ky",
      "18kw",
      "18ky",
      "pt"
    ],
    "estWeightG": 4.2,
    "laborUsd": 85,
    "leadDays": 12,
    "availableForSale": true,
    "published": true,
    "supplierEvidence": "https://dianamjewels.com/products/lab-grown-diamond-marquise-pear-cut-flower-pendant?variant=47022501593188",
    "firstQuoteAt": "2026-06-27",
    "name": {
      "en": "Marquise Pear Flower Pendant",
      "ko": "마퀴즈 페어 플라워 펜던트",
      "zh": "马眼形梨形花朵吊坠",
      "es": "Colgante floral marquise y pera"
    },
    "detailLabel": {
      "en": "Custom starter design",
      "ko": "맞춤 시작 디자인",
      "zh": "定制起点设计",
      "es": "Diseño inicial personalizado"
    },
    "description": {
      "en": "This is a sample starting point, not a limit. Share references and we can adjust shape, scale, stones, metal, and finish after review.",
      "ko": "이 디자인은 제한이 아니라 시작점입니다. 원하는 레퍼런스를 보내주시면 형태, 크기, 스톤, 메탈, 마감을 검토 후 조정할 수 있습니다.",
      "zh": "这是起点样例，不是限制。上传参考后，我们可评估并调整造型、尺寸、宝石、金属与细节。",
      "es": "Este diseño es un punto de partida, no un límite. Comparte referencias y ajustamos forma, escala, piedras, metal y acabado tras revisar."
    },
    "flexibleText": {
      "en": "Chain, length, pendant scale",
      "ko": "체인, 길이, 펜던트 크기",
      "zh": "链型、长度、吊坠比例",
      "es": "Cadena, largo, escala del colgante"
    },
    "beforeProductionText": {
      "en": "Quote and CAD approval",
      "ko": "견적 및 CAD 승인",
      "zh": "报价与 CAD 确认",
      "es": "Cotización y aprobación CAD"
    }
  },
  {
    "id": "NECK-007",
    "category": "necklace",
    "subcategory": "tennisNecklace",
    "coverImage": "/assets/designs/NCGXK4149Q-RG-RB-WH-700-M0.jpg",
    "media": [
      {
        "kind": "image",
        "src": "/assets/designs/NCGXK4149Q-RG-RB-WH-700-M0.jpg"
      },
      {
        "kind": "image",
        "src": "/assets/designs/NCGXK4149Q-RG-RB-WH-700-M4.jpg"
      },
      {
        "kind": "image",
        "src": "/assets/designs/NCGXK4149Q-RG-RB-WH-700-M1.jpg"
      }
    ],
    "mediaComplete": true,
    "metalOptions": [
      "14kw",
      "14ky",
      "18kw",
      "18ky",
      "pt"
    ],
    "estWeightG": 4.2,
    "laborUsd": 85,
    "leadDays": 12,
    "availableForSale": true,
    "published": true,
    "supplierEvidence": "https://www.grownbrilliance.com/5-ctw-round-lab-grown-diamond-four-prong-tennis-necklace-14k-rose-gold/pid/NECUDN03480GP2-18",
    "firstQuoteAt": "2026-06-27",
    "name": {
      "en": "Four-Prong Tennis Necklace",
      "ko": "4프롱 테니스 네크리스",
      "zh": "四爪网球项链",
      "es": "Collar tenis de 4 garras"
    },
    "detailLabel": {
      "en": "Custom starter design",
      "ko": "맞춤 시작 디자인",
      "zh": "定制起点设计",
      "es": "Diseño inicial personalizado"
    },
    "description": {
      "en": "This is a sample starting point, not a limit. Share references and we can adjust shape, scale, stones, metal, and finish after review.",
      "ko": "이 디자인은 제한이 아니라 시작점입니다. 원하는 레퍼런스를 보내주시면 형태, 크기, 스톤, 메탈, 마감을 검토 후 조정할 수 있습니다.",
      "zh": "这是起点样例，不是限制。上传参考后，我们可评估并调整造型、尺寸、宝石、金属与细节。",
      "es": "Este diseño es un punto de partida, no un límite. Comparte referencias y ajustamos forma, escala, piedras, metal y acabado tras revisar."
    },
    "flexibleText": {
      "en": "Chain, length, pendant scale",
      "ko": "체인, 길이, 펜던트 크기",
      "zh": "链型、长度、吊坠比例",
      "es": "Cadena, largo, escala del colgante"
    },
    "beforeProductionText": {
      "en": "Quote and CAD approval",
      "ko": "견적 및 CAD 승인",
      "zh": "报价与 CAD 确认",
      "es": "Cotización y aprobación CAD"
    }
  },
  {
    "id": "NECK-008",
    "category": "necklace",
    "subcategory": "stationNecklace",
    "coverImage": "/assets/designs/NCGKN29498-WG-RB-WH-200-M0-1.jpg",
    "media": [
      {
        "kind": "image",
        "src": "/assets/designs/NCGKN29498-WG-RB-WH-200-M0-1.jpg"
      },
      {
        "kind": "image",
        "src": "/assets/designs/NCGKN29498-WG-RB-WH-200-M4.jpg"
      },
      {
        "kind": "image",
        "src": "/assets/designs/NCGKN29498-WG-RB-WH-200-M2-1.jpg"
      },
      {
        "kind": "image",
        "src": "/assets/designs/NCGKN29498-WG-RB-WH-200-M1-1.jpg"
      }
    ],
    "mediaComplete": true,
    "metalOptions": [
      "14kw",
      "14ky",
      "18kw",
      "18ky",
      "pt"
    ],
    "estWeightG": 4.2,
    "laborUsd": 85,
    "leadDays": 12,
    "availableForSale": true,
    "published": true,
    "supplierEvidence": "https://www.grownbrilliance.com/2-ctw-round-lab-grown-diamond-station-necklace-14k-white-gold/pid/NECKN29498-GW2-16?cq_src=google_ads&cq_cmp=22123575278&cq_con=178662484052&cq_term=&cq_med=pla_with_promotion&cq_plac=&cq_net=g&cq_plt=gp&gad_source=1&gad_campaignid=22123575278&gclid=CjwKCAjwl97RBhBWEiwAa9rbXfkzl0yBNueHp24spA_vTL_zTFZp8rUDss-nkguF0iLgLRjCEY2cORoC_7IQAvD_BwE",
    "firstQuoteAt": "2026-06-27",
    "name": {
      "en": "Station Necklace",
      "ko": "스테이션 네크리스",
      "zh": "站钻项链",
      "es": "Collar station"
    },
    "detailLabel": {
      "en": "Custom starter design",
      "ko": "맞춤 시작 디자인",
      "zh": "定制起点设计",
      "es": "Diseño inicial personalizado"
    },
    "description": {
      "en": "This is a sample starting point, not a limit. Share references and we can adjust shape, scale, stones, metal, and finish after review.",
      "ko": "이 디자인은 제한이 아니라 시작점입니다. 원하는 레퍼런스를 보내주시면 형태, 크기, 스톤, 메탈, 마감을 검토 후 조정할 수 있습니다.",
      "zh": "这是起点样例，不是限制。上传参考后，我们可评估并调整造型、尺寸、宝石、金属与细节。",
      "es": "Este diseño es un punto de partida, no un límite. Comparte referencias y ajustamos forma, escala, piedras, metal y acabado tras revisar."
    },
    "flexibleText": {
      "en": "Chain, length, pendant scale",
      "ko": "체인, 길이, 펜던트 크기",
      "zh": "链型、长度、吊坠比例",
      "es": "Cadena, largo, escala del colgante"
    },
    "beforeProductionText": {
      "en": "Quote and CAD approval",
      "ko": "견적 및 CAD 승인",
      "zh": "报价与 CAD 确认",
      "es": "Cotización y aprobación CAD"
    }
  },
  {
    "id": "NECK-009",
    "category": "necklace",
    "subcategory": "pendant",
    "coverImage": "/assets/designs/PNGKP0960-RG-RB-WH-300-M0.jpg",
    "media": [
      {
        "kind": "image",
        "src": "/assets/designs/PNGKP0960-RG-RB-WH-300-M0.jpg"
      }
    ],
    "mediaComplete": true,
    "metalOptions": [
      "14kw",
      "14ky",
      "18kw",
      "18ky",
      "pt"
    ],
    "estWeightG": 4.2,
    "laborUsd": 85,
    "leadDays": 12,
    "availableForSale": true,
    "published": true,
    "supplierEvidence": "https://www.grownbrilliance.com/3-ctw-round-lab-grown-diamond-cross-pendant-with-adjustable-chain-14k-rose-gold/pid/PENKP0960-GP2?algoliaQueryId=0043d09c1b5739ede681cb946715a36a&category_id=41",
    "firstQuoteAt": "2026-06-27",
    "name": {
      "en": "Diamond Cross Pendant",
      "ko": "다이아몬드 크로스 펜던트",
      "zh": "钻石十字吊坠",
      "es": "Colgante cruz de diamantes"
    },
    "detailLabel": {
      "en": "Custom starter design",
      "ko": "맞춤 시작 디자인",
      "zh": "定制起点设计",
      "es": "Diseño inicial personalizado"
    },
    "description": {
      "en": "This is a sample starting point, not a limit. Share references and we can adjust shape, scale, stones, metal, and finish after review.",
      "ko": "이 디자인은 제한이 아니라 시작점입니다. 원하는 레퍼런스를 보내주시면 형태, 크기, 스톤, 메탈, 마감을 검토 후 조정할 수 있습니다.",
      "zh": "这是起点样例，不是限制。上传参考后，我们可评估并调整造型、尺寸、宝石、金属与细节。",
      "es": "Este diseño es un punto de partida, no un límite. Comparte referencias y ajustamos forma, escala, piedras, metal y acabado tras revisar."
    },
    "flexibleText": {
      "en": "Chain, length, pendant scale",
      "ko": "체인, 길이, 펜던트 크기",
      "zh": "链型、长度、吊坠比例",
      "es": "Cadena, largo, escala del colgante"
    },
    "beforeProductionText": {
      "en": "Quote and CAD approval",
      "ko": "견적 및 CAD 승인",
      "zh": "报价与 CAD 确认",
      "es": "Cotización y aprobación CAD"
    }
  },
  {
    "id": "NECK-010",
    "category": "necklace",
    "subcategory": "pendant",
    "coverImage": "/assets/designs/NJOP7967-WG-M0.jpg",
    "media": [
      {
        "kind": "image",
        "src": "/assets/designs/NJOP7967-WG-M0.jpg"
      },
      {
        "kind": "image",
        "src": "/assets/designs/NJOP7967-WG-M1.jpg"
      }
    ],
    "mediaComplete": true,
    "metalOptions": [
      "14kw",
      "14ky",
      "18kw",
      "18ky",
      "pt"
    ],
    "estWeightG": 4.2,
    "laborUsd": 85,
    "leadDays": 12,
    "availableForSale": true,
    "published": true,
    "supplierEvidence": "https://www.grownbrilliance.com/1-2-3-ctw-shield-lab-grown-diamond-cross-statement-pendant-14k-white-gold/pid/PENJOP7967-GW2-18?algoliaQueryId=0043d09c1b5739ede681cb946715a36a&category_id=41",
    "firstQuoteAt": "2026-06-27",
    "name": {
      "en": "Shield Diamond Cross Statement Pendant",
      "ko": "쉴드 다이아몬드 크로스 펜던트",
      "zh": "盾形钻石十字吊坠",
      "es": "Colgante cruz shield"
    },
    "detailLabel": {
      "en": "Custom starter design",
      "ko": "맞춤 시작 디자인",
      "zh": "定制起点设计",
      "es": "Diseño inicial personalizado"
    },
    "description": {
      "en": "This is a sample starting point, not a limit. Share references and we can adjust shape, scale, stones, metal, and finish after review.",
      "ko": "이 디자인은 제한이 아니라 시작점입니다. 원하는 레퍼런스를 보내주시면 형태, 크기, 스톤, 메탈, 마감을 검토 후 조정할 수 있습니다.",
      "zh": "这是起点样例，不是限制。上传参考后，我们可评估并调整造型、尺寸、宝石、金属与细节。",
      "es": "Este diseño es un punto de partida, no un límite. Comparte referencias y ajustamos forma, escala, piedras, metal y acabado tras revisar."
    },
    "flexibleText": {
      "en": "Chain, length, pendant scale",
      "ko": "체인, 길이, 펜던트 크기",
      "zh": "链型、长度、吊坠比例",
      "es": "Cadena, largo, escala del colgante"
    },
    "beforeProductionText": {
      "en": "Quote and CAD approval",
      "ko": "견적 및 CAD 승인",
      "zh": "报价与 CAD 确认",
      "es": "Cotización y aprobación CAD"
    }
  }
];
